import enLegacy from "@/lib/i18n/legacy/en.json";
import esLegacy from "@/lib/i18n/legacy/es.json";
import ptLegacy from "@/lib/i18n/legacy/pt.json";
import type { SupportedLanguage } from "@/lib/site";

const BLOG_ARTICLE_CONTENT: Record<SupportedLanguage, Record<string, string>> = {
  pt: {
    blog_scales_clt_article_html: ptLegacy.blog_scales_clt_article_html,
    blog_scale_12x36_article_html: ptLegacy.blog_scale_12x36_article_html,
    blog_scale_6x1_article_html: ptLegacy.blog_scale_6x1_article_html,
    blog_business_days_article_html: ptLegacy.blog_business_days_article_html,
    blog_fifth_business_day_article_html: ptLegacy.blog_fifth_business_day_article_html,
    blog_night_additional_article_html: ptLegacy.blog_night_additional_article_html,
  },
  en: {
    blog_scales_clt_article_html: enLegacy.blog_scales_clt_article_html,
    blog_scale_12x36_article_html: enLegacy.blog_scale_12x36_article_html,
    blog_scale_6x1_article_html: enLegacy.blog_scale_6x1_article_html,
    blog_business_days_article_html: enLegacy.blog_business_days_article_html,
    blog_fifth_business_day_article_html: enLegacy.blog_fifth_business_day_article_html,
    blog_night_additional_article_html: enLegacy.blog_night_additional_article_html,
  },
  es: {
    blog_scales_clt_article_html: esLegacy.blog_scales_clt_article_html,
    blog_scale_12x36_article_html: esLegacy.blog_scale_12x36_article_html,
    blog_scale_6x1_article_html: esLegacy.blog_scale_6x1_article_html,
    blog_business_days_article_html: esLegacy.blog_business_days_article_html,
    blog_fifth_business_day_article_html: esLegacy.blog_fifth_business_day_article_html,
    blog_night_additional_article_html: esLegacy.blog_night_additional_article_html,
  },
};

const CUSTOM_BLOG_ARTICLE_CONTENT: Record<SupportedLanguage, Record<string, string>> = {
  pt: {
    blog_business_days_2026_months_article_html:
      "<h1 class='text-2xl md:text-3xl font-extrabold mb-4'>Quantos Dias Uteis Tem Cada Mes de 2026</h1><p>Quem trabalha com prazos, folha, faturamento e entregas costuma precisar da mesma resposta varias vezes ao longo do ano: quantos dias uteis tem cada mes? Em 2026, essa leitura continua importante porque a quantidade de dias uteis muda quando o mes recebe feriado nacional em dia de semana.</p><h2>Visao rapida de 2026</h2><ul><li><strong>Janeiro</strong> tem 21 dias uteis, com o feriado de 1 de janeiro em uma quinta-feira.</li><li><strong>Abril</strong> perde um dia util por causa da Sexta-Feira Santa.</li><li><strong>Maio</strong> tambem perde um dia util com o Dia do Trabalho em uma sexta-feira.</li><li><strong>Setembro</strong>, <strong>outubro</strong> e <strong>novembro</strong> recebem feriados nacionais em segunda-feira, o que afeta planejamento e fechamento.</li><li><strong>Dezembro</strong> perde um dia util com o Natal em uma sexta-feira.</li></ul><h2>Como consultar cada mes</h2><p>Em vez de fazer uma conta manual toda vez, use as paginas indexaveis do Datas Uteis para abrir o ano completo e depois entrar no mes especifico. Assim voce ve dias uteis, fins de semana, feriados e o 5o dia util na mesma estrutura.</p><div class='card p-5 my-6'><h2 class='font-bold text-lg mb-2'>Paginas uteis</h2><div class='flex flex-wrap gap-3'><a href='/dias-uteis/2026/' class='btn-primary blog-cta'><span>Dias uteis de 2026</span> &rarr;</a><a href='/calcular/' class='btn-secondary blog-cta'><span>Calcular intervalo</span></a></div></div><h2>Quando essa pagina ajuda mais</h2><ul><li>Planejamento de folha e pagamento.</li><li>Definicao de metas e SLAs por mes.</li><li>Comparacao entre meses com e sem feriado.</li><li>Conferencia do impacto do 5o dia util.</li></ul><h2>Perguntas frequentes</h2><div class='blog-faq card p-5'><details open><summary>Os dias uteis mudam de um mes para outro em 2026?</summary><p>Sim. Feriados nacionais em dias de semana mudam a contagem de dias uteis de cada mes.</p></details><details><summary>Posso abrir o detalhe de janeiro, fevereiro e outros meses?</summary><p>Sim. Cada linha da pagina anual leva para uma pagina mensal indexavel com mais contexto.</p></details><details><summary>Essa consulta serve para anos futuros?</summary><p>Sim. A estrutura do site foi feita para anos passados, ano atual e anos futuros.</p></details></div>",
    blog_long_holidays_2026_article_html:
      "<h1 class='text-2xl md:text-3xl font-extrabold mb-4'>Feriados Prolongados de 2026</h1><p>Feriado prolongado interessa para quem organiza folgas, viagens, atendimento, cobertura operacional e calendario comercial. Em 2026, varios feriados nacionais caem em segunda-feira ou sexta-feira, criando janelas mais longas sem precisar de emenda complexa.</p><h2>Os principais feriados prolongados do ano</h2><ul><li><strong>Sexta-Feira Santa</strong> em 3 de abril, na sexta-feira.</li><li><strong>Dia do Trabalho</strong> em 1 de maio, na sexta-feira.</li><li><strong>Independencia do Brasil</strong> em 7 de setembro, na segunda-feira.</li><li><strong>Nossa Senhora Aparecida</strong> em 12 de outubro, na segunda-feira.</li><li><strong>Finados</strong> em 2 de novembro, na segunda-feira.</li><li><strong>Consciencia Negra</strong> em 20 de novembro, na sexta-feira.</li><li><strong>Natal</strong> em 25 de dezembro, na sexta-feira.</li></ul><h2>Feriados que pedem mais cuidado</h2><p><strong>Tiradentes</strong>, em 21 de abril de 2026, cai em uma terça-feira. Ele pode gerar uma ponte na segunda, mas isso depende da politica da empresa. <strong>Proclamacao da Republica</strong>, em 15 de novembro, cai em um domingo e perde peso para pausas mais longas.</p><h2>Como usar isso no planejamento</h2><ul><li>Revise cobertura da equipe antes das segundas e sextas com feriado.</li><li>Antecipe prazos internos quando a semana ficar mais curta.</li><li>Use a calculadora de dias uteis para validar entregas e fechamento.</li></ul><section class='card p-5 mt-8'><h2 class='font-bold text-lg mb-2'>Abrir calendario 2026</h2><p class='text-sm text-surface-500 mb-4'>Consulte o calendario completo de 2026 com feriados e navegacao por mes.</p><div class='flex flex-wrap gap-3'><a href='/calendario/2026/' class='btn-primary blog-cta'><span>Calendario 2026</span> &rarr;</a><a href='/dias-uteis/2026/' class='btn-secondary blog-cta'><span>Dias uteis de 2026</span></a></div></section><h2>Perguntas frequentes</h2><div class='blog-faq card p-5'><details open><summary>2026 tem muitos feriados prolongados?</summary><p>Sim. O calendario de 2026 traz varias sextas e segundas com feriado nacional.</p></details><details><summary>Tiradentes gera feriado prolongado?</summary><p>Ele cai em uma terca-feira. A possibilidade de emenda depende da empresa ou do orgao.</p></details><details><summary>Qual pagina ajuda a ver o impacto nos dias uteis?</summary><p>A pagina anual de dias uteis de 2026 mostra mes a mes a quantidade de dias uteis, fins de semana e feriados.</p></details></div>",
    blog_business_days_excel_article_html:
      "<h1 class='text-2xl md:text-3xl font-extrabold mb-4'>Como Calcular Dias Uteis no Excel</h1><p>Muita gente procura o Excel como primeira alternativa para calcular prazo. Ele ajuda, mas a formula precisa estar alinhada com a regra usada no seu processo, especialmente quando entram feriados e quando o sabado nao conta como dia util.</p><h2>Formula mais comum</h2><p>No Excel em portugues, a funcao mais usada e <strong>DIATRABALHOTOTAL</strong>. Ela calcula quantos dias uteis existem entre duas datas e aceita uma lista de feriados para abater da conta.</p><div class='card p-5 my-6'><p class='font-mono text-sm'>=DIATRABALHOTOTAL(A2;B2;F2:F20)</p></div><p>Nesse exemplo, <strong>A2</strong> e a data inicial, <strong>B2</strong> e a data final e <strong>F2:F20</strong> guarda os feriados.</p><h2>Somar dias uteis no Excel</h2><p>Para achar a data final de um prazo, a funcao mais comum e <strong>DIATRABALHO</strong>.</p><div class='card p-5 my-6'><p class='font-mono text-sm'>=DIATRABALHO(A2;15;F2:F20)</p></div><p>Ela pega uma data base e soma a quantidade de dias uteis desejada.</p><h2>Onde a ferramenta online ajuda mais</h2><ul><li>Quando voce precisa validar o resultado sem montar planilha.</li><li>Quando quer comparar meses e anos rapidamente.</li><li>Quando precisa enxergar feriados e 5o dia util em paginas separadas.</li></ul><section class='card p-5 mt-8'><h2 class='font-bold text-lg mb-2'>Calcular agora</h2><p class='text-sm text-surface-500 mb-4'>Use a calculadora online para contar, somar e subtrair dias uteis sem montar formula.</p><a href='/calcular/' class='btn-primary blog-cta'><span>Abrir calculadora</span> &rarr;</a></section><h2>Perguntas frequentes</h2><div class='blog-faq card p-5'><details open><summary>O Excel considera feriados sozinho?</summary><p>Nao. Voce precisa informar uma lista de feriados para a formula descontar essas datas.</p></details><details><summary>Posso somar dias uteis no Excel?</summary><p>Sim. A funcao DIATRABALHO serve para partir de uma data e chegar a outra contando apenas dias uteis.</p></details><details><summary>Vale conferir o resultado em uma calculadora online?</summary><p>Sim. Isso ajuda a evitar erro de formula e melhora a leitura do prazo final.</p></details></div>",
    blog_saturday_business_day_article_html:
      "<h1 class='text-2xl md:text-3xl font-extrabold mb-4'>Sabado Conta Como Dia Util?</h1><p>Essa e uma das perguntas mais comuns em prazos, folha, entrega e rotinas administrativas. A resposta curta e: <strong>depende do contexto</strong>. Em boa parte dos calculos operacionais, bancarios e de prazo, sabado nao entra como dia util. Mas ha situacoes especificas em que a regra aplicada pode ser outra.</p><h2>Leitura mais comum</h2><p>No uso mais frequente do Datas Uteis, sabado nao entra como dia util. Essa e a leitura adotada em grande parte dos fluxos administrativos e de planejamento de prazo.</p><h2>Quando o contexto muda</h2><ul><li>Empresas que operam tambem aos sabados.</li><li>Regras contratuais que definem sabado como dia de atendimento.</li><li>Fluxos logísticos e comerciais com janela especial de entrega.</li></ul><p>Por isso, a melhor pratica e confirmar a regra concreta do seu processo antes de fechar um prazo relevante.</p><h2>Como tratar isso na pratica</h2><p>Se o seu processo nao conta sabado, use a leitura padrao. Se o sabado entra na operacao, ajuste a calculadora para esse cenario e compare o resultado.</p><section class='card p-5 mt-8'><h2 class='font-bold text-lg mb-2'>Comparar na calculadora</h2><p class='text-sm text-surface-500 mb-4'>Abra a calculadora e teste o mesmo intervalo com ou sem sabado na conta.</p><a href='/calcular/' class='btn-primary blog-cta'><span>Calcular dias uteis</span> &rarr;</a></section><h2>Perguntas frequentes</h2><div class='blog-faq card p-5'><details open><summary>No Datas Uteis, sabado conta como dia util?</summary><p>Na leitura padrao do site, nao. Mas a calculadora permite simular o cenario com sabado util.</p></details><details><summary>Posso usar a mesma regra para qualquer prazo?</summary><p>Nao. O correto e validar a regra especifica do seu contrato, empresa ou processo.</p></details><details><summary>Como comparar os dois cenarios?</summary><p>Use a calculadora com a opcao de contar sabado como dia util ligada e desligada.</p></details></div>",
    blog_deadline_counting_article_html:
      "<h1 class='text-2xl md:text-3xl font-extrabold mb-4'>Como Contar Prazos em Dias Uteis</h1><p>Contar prazo parece simples ate o momento em que fim de semana, feriado e regra de sabado entram na conta. Em rotina administrativa, contratos, folha, atendimento e operacoes internas, o erro mais comum e misturar <strong>dias uteis</strong> com <strong>dias corridos</strong>.</p><h2>Comece pela regra certa</h2><p>Antes de contar qualquer prazo, confirme se a regra usada no seu processo fala em dias uteis ou dias corridos. Dias corridos incluem todo o calendario. Dias uteis, na leitura mais comum do site, excluem sabados, domingos e feriados nacionais.</p><h2>Passo a passo para nao errar</h2><ol><li>Defina a data inicial e a data final desejada.</li><li>Confirme se o sabado entra ou nao entra na operacao.</li><li>Desconte fins de semana e feriados aplicaveis.</li><li>Se o prazo for para frente, some dias uteis ate chegar na data final.</li><li>Se o prazo for para tras, subtraia dias uteis a partir da data limite.</li></ol><h2>Quando a calculadora ajuda mais</h2><p>A calculadora do Datas Uteis e util quando voce precisa comparar cenarios rapidamente, validar a data final de um prazo ou descobrir quando um processo deveria ter comecado.</p><section class='card p-5 mt-8'><h2 class='font-bold text-lg mb-2'>Ferramentas relacionadas</h2><div class='flex flex-wrap gap-3'><a href='/calcular/' class='btn-primary blog-cta'><span>Calcular dias uteis</span> &rarr;</a><a href='/dias-uteis/' class='btn-secondary blog-cta'><span>Ver paginas por mes</span></a><a href='/blog/sabado-conta-como-dia-util/' class='btn-secondary blog-cta'><span>Regra do sabado</span></a></div></section><h2>Perguntas frequentes</h2><div class='blog-faq card p-5'><details open><summary>Prazo em dias uteis e igual a prazo em dias corridos?</summary><p>Nao. Dias corridos incluem todo o calendario; dias uteis excluem fins de semana e feriados na leitura padrao.</p></details><details><summary>Como descobrir a data final de um prazo?</summary><p>Use a calculadora no modo de somar dias uteis a partir de uma data base.</p></details><details><summary>Como descobrir quando o prazo deveria ter comecado?</summary><p>Use o modo de subtrair dias uteis a partir da data limite.</p></details></div>",
    blog_schedule_building_article_html:
      "<h1 class='text-2xl md:text-3xl font-extrabold mb-4'>Como Montar Escala de Trabalho</h1><p>Montar uma escala de trabalho nao e apenas distribuir nomes em um calendario. Uma escala boa precisa equilibrar cobertura, descanso, feriados, modelo de jornada e a realidade da operacao. Quando isso nao acontece, o problema aparece em forma de deficit, hora extra inesperada e folga mal distribuida.</p><h2>O que definir antes de montar a escala</h2><ul><li>Janela de operacao: quais horarios precisam de cobertura.</li><li>Quantidade de postos simultaneos: quantas pessoas devem estar ativas ao mesmo tempo.</li><li>Modelo de jornada: 5x2, 6x1, 12x36 ou outro arranjo.</li><li>Tratamento de sabados, domingos e feriados.</li><li>Quantidade real de pessoas disponiveis.</li></ul><h2>Por que testar mais de um modelo</h2><p>Muitas operacoes tentam encaixar tudo em um unico desenho e depois descobrem que a cobertura mensal ficou curta. Comparar dois ou tres modelos antes de fechar a escala ajuda a enxergar custo, descanso e cobertura com mais clareza.</p><h2>Use simulacao antes de fechar</h2><p>O simulador do Datas Uteis ajuda a testar mes, quantidade de turnos, postos simultaneos e feriados em uma mesma leitura. Isso deixa mais facil perceber onde a equipe fica apertada ou sobra cobertura.</p><section class='card p-5 mt-8'><h2 class='font-bold text-lg mb-2'>Abrir simulador</h2><div class='flex flex-wrap gap-3'><a href='/escala/' class='btn-primary blog-cta'><span>Simular escala</span> &rarr;</a><a href='/blog/escala-12x36-como-funciona/' class='btn-secondary blog-cta'><span>Entender 12x36</span></a><a href='/blog/escalas-de-trabalho-clt/' class='btn-secondary blog-cta'><span>Ver escalas CLT</span></a></div></section><h2>Perguntas frequentes</h2><div class='blog-faq card p-5'><details open><summary>Qual e a primeira informacao para montar uma escala?</summary><p>Comece pela janela de operacao e pela quantidade de postos que precisam ficar cobertos ao mesmo tempo.</p></details><details><summary>Vale comparar 12x36 e 6x1 antes de decidir?</summary><p>Sim. Modelos diferentes mudam cobertura, descanso e quantidade minima de pessoas.</p></details><details><summary>Feriados precisam entrar na simulacao?</summary><p>Sim. Eles podem mudar bastante a cobertura do mes e a distribuicao de folgas.</p></details></div>",
    blog_logic_games_benefits_article_html:
      "<h1 class='text-2xl md:text-3xl font-extrabold mb-4'>Beneficios dos Jogos de Logica</h1><p>Jogos de logica nao precisam ser longos para serem uteis. Uma rodada curta de Sudoku, palavras cruzadas ou caca-palavras pode funcionar como pausa mental focada, especialmente quando voce quer mudar o ritmo sem cair em distraicao excessiva.</p><h2>O que esses jogos estimulam</h2><ul><li><strong>Sudoku</strong> pede leitura de padroes, atencao e deducao.</li><li><strong>Palavras cruzadas</strong> trabalham vocabulario, leitura curta e associacao entre pistas.</li><li><strong>Caca-palavras</strong> ajuda em varredura visual, foco e reconhecimento rapido.</li></ul><h2>Pausa curta, sem sair da tela</h2><p>Quando a ideia e descansar por alguns minutos, jogos leves funcionam melhor do que uma navegacao aberta e sem objetivo. Eles criam uma tarefa fechada, com inicio, meio e fim, o que costuma ser mais facil de controlar.</p><h2>Sem promessas exageradas</h2><p>Jogos de logica podem ajudar foco e leitura de padroes no dia a dia, mas nao substituem descanso real, estudo formal ou cuidado profissional. O ganho aqui e pratico: uma pausa curta, organizada e com desafio leve.</p><section class='card p-5 mt-8'><h2 class='font-bold text-lg mb-2'>Experimentar agora</h2><div class='flex flex-wrap gap-3'><a href='/jogos/sudoku/' class='btn-primary blog-cta'><span>Jogar Sudoku</span> &rarr;</a><a href='/jogos/palavras-cruzadas/' class='btn-secondary blog-cta'><span>Palavras cruzadas</span></a><a href='/jogos/caca-palavras/' class='btn-secondary blog-cta'><span>Caca-palavras</span></a></div></section><h2>Perguntas frequentes</h2><div class='blog-faq card p-5'><details open><summary>Qual jogo de logica e melhor para comecar?</summary><p>Depende do seu estilo. Sudoku foca mais em deducao numerica; palavras cruzadas e caca-palavras sao mais textuais e visuais.</p></details><details><summary>Esses jogos servem para pausas curtas?</summary><p>Sim. Eles funcionam bem em intervalos pequenos porque a rodada pode ser retomada ou reiniciada com facilidade.</p></details><details><summary>Jogos de logica substituem estudo ou descanso real?</summary><p>Nao. Eles servem melhor como apoio leve, nao como substituto de descanso ou aprendizado estruturado.</p></details></div>",
  },
  en: {},
  es: {},
};

export function getBlogArticleHtml(language: SupportedLanguage, key: string) {
  return (
    CUSTOM_BLOG_ARTICLE_CONTENT[language][key] ??
    CUSTOM_BLOG_ARTICLE_CONTENT.pt[key] ??
    BLOG_ARTICLE_CONTENT[language][key] ??
    BLOG_ARTICLE_CONTENT.pt[key] ??
    ""
  );
}
