/**
 * Complete world country dataset for the World Clock utility.
 * Each country includes: id, continent, name (pt), capital, coordinates,
 * primary timezone, alternate timezones, political regime, population, languages.
 *
 * Continent values: "america" | "asia" | "africa" | "antarctica" | "europe" | "oceania"
 */

export type Continent =
  | "america"
  | "asia"
  | "africa"
  | "antarctica"
  | "europe"
  | "oceania";

export const CONTINENT_ORDER: Continent[] = [
  "america",
  "asia",
  "africa",
  "antarctica",
  "europe",
  "oceania",
];

export interface CountryTimezoneOption {
  id: string;
  label: string;
  timezone: string;
}

export interface WorldCountryDefinition {
  id: string;
  continent: Continent;
  name: string;
  capital: string;
  capitalLatitude: number;
  capitalLongitude: number;
  capitalTimezone: string;
  timezones: CountryTimezoneOption[];
  politicalRegime: string;
  population: number | null;
  languages: string[];
  aliases?: string[];
}

export const WORLD_CLOCK_COUNTRIES: WorldCountryDefinition[] = [
  // ════════════════════════════════════════════
  // AMÉRICA
  // ════════════════════════════════════════════
  {
    id: "ag",
    continent: "america",
    name: "Antígua e Barbuda",
    capital: "Saint John's",
    capitalLatitude: 17.1175,
    capitalLongitude: -61.8456,
    capitalTimezone: "America/Antigua",
    timezones: [{ id: "capital", label: "Saint John's (AST)", timezone: "America/Antigua" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 100772,
    languages: ["Inglês"],
  },
  {
    id: "ar",
    continent: "america",
    name: "Argentina",
    capital: "Buenos Aires",
    capitalLatitude: -34.6037,
    capitalLongitude: -58.3816,
    capitalTimezone: "America/Argentina/Buenos_Aires",
    timezones: [{ id: "capital", label: "Buenos Aires (ART)", timezone: "America/Argentina/Buenos_Aires" }],
    politicalRegime: "República federal presidencialista",
    population: 46234830,
    languages: ["Espanhol"],
  },
  {
    id: "bs",
    continent: "america",
    name: "Bahamas",
    capital: "Nassau",
    capitalLatitude: 25.0480,
    capitalLongitude: -77.3554,
    capitalTimezone: "America/Nassau",
    timezones: [{ id: "capital", label: "Nassau (EST/EDT)", timezone: "America/Nassau" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 412623,
    languages: ["Inglês"],
  },
  {
    id: "bb",
    continent: "america",
    name: "Barbados",
    capital: "Bridgetown",
    capitalLatitude: 13.0969,
    capitalLongitude: -59.6145,
    capitalTimezone: "America/Barbados",
    timezones: [{ id: "capital", label: "Bridgetown (AST)", timezone: "America/Barbados" }],
    politicalRegime: "República parlamentar",
    population: 281995,
    languages: ["Inglês"],
  },
  {
    id: "bz",
    continent: "america",
    name: "Belize",
    capital: "Belmopan",
    capitalLatitude: 17.2510,
    capitalLongitude: -88.7590,
    capitalTimezone: "America/Belize",
    timezones: [{ id: "capital", label: "Belmopan (CST)", timezone: "America/Belize" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 405272,
    languages: ["Inglês"],
  },
  {
    id: "bo",
    continent: "america",
    name: "Bolívia",
    capital: "Sucre",
    capitalLatitude: -19.0196,
    capitalLongitude: -65.2619,
    capitalTimezone: "America/La_Paz",
    timezones: [{ id: "capital", label: "Sucre (BOT)", timezone: "America/La_Paz" }],
    politicalRegime: "República presidencialista",
    population: 12006031,
    languages: ["Espanhol", "Quíchua", "Aimará"],
  },
  {
    id: "br",
    continent: "america",
    name: "Brasil",
    capital: "Brasília",
    capitalLatitude: -15.7939,
    capitalLongitude: -47.8828,
    capitalTimezone: "America/Sao_Paulo",
    timezones: [
      { id: "capital", label: "Brasília (BRT)", timezone: "America/Sao_Paulo" },
      { id: "manaus", label: "Manaus (AMT)", timezone: "America/Manaus" },
      { id: "rio-branco", label: "Rio Branco (ACT)", timezone: "America/Rio_Branco" },
      { id: "noronha", label: "Fernando de Noronha (FNT)", timezone: "America/Noronha" },
    ],
    politicalRegime: "República federativa presidencialista",
    population: 212583750,
    languages: ["Português"],
  },
  {
    id: "ca",
    continent: "america",
    name: "Canadá",
    capital: "Ottawa",
    capitalLatitude: 45.4215,
    capitalLongitude: -75.6972,
    capitalTimezone: "America/Toronto",
    timezones: [
      { id: "capital", label: "Ottawa (ET)", timezone: "America/Toronto" },
      { id: "winnipeg", label: "Winnipeg (CT)", timezone: "America/Winnipeg" },
      { id: "edmonton", label: "Edmonton (MT)", timezone: "America/Edmonton" },
      { id: "vancouver", label: "Vancouver (PT)", timezone: "America/Vancouver" },
      { id: "halifax", label: "Halifax (AT)", timezone: "America/Halifax" },
      { id: "stjohns", label: "St. John's (NT)", timezone: "America/St_Johns" },
    ],
    politicalRegime: "Monarquia constitucional parlamentar federal",
    population: 41740538,
    languages: ["Inglês", "Francês"],
  },
  {
    id: "cl",
    continent: "america",
    name: "Chile",
    capital: "Santiago",
    capitalLatitude: -33.4489,
    capitalLongitude: -70.6693,
    capitalTimezone: "America/Santiago",
    timezones: [
      { id: "capital", label: "Santiago (CLT/CLST)", timezone: "America/Santiago" },
      { id: "easter", label: "Ilha de Páscoa (EAST)", timezone: "Pacific/Easter" },
    ],
    politicalRegime: "República presidencialista",
    population: 19493184,
    languages: ["Espanhol"],
  },
  {
    id: "co",
    continent: "america",
    name: "Colômbia",
    capital: "Bogotá",
    capitalLatitude: 4.7110,
    capitalLongitude: -74.0721,
    capitalTimezone: "America/Bogota",
    timezones: [{ id: "capital", label: "Bogotá (COT)", timezone: "America/Bogota" }],
    politicalRegime: "República presidencialista",
    population: 51874024,
    languages: ["Espanhol"],
  },
  {
    id: "cr",
    continent: "america",
    name: "Costa Rica",
    capital: "San José",
    capitalLatitude: 9.9281,
    capitalLongitude: -84.0907,
    capitalTimezone: "America/Costa_Rica",
    timezones: [{ id: "capital", label: "San José (CST)", timezone: "America/Costa_Rica" }],
    politicalRegime: "República presidencialista",
    population: 5180829,
    languages: ["Espanhol"],
  },
  {
    id: "cu",
    continent: "america",
    name: "Cuba",
    capital: "Havana",
    capitalLatitude: 23.1136,
    capitalLongitude: -82.3666,
    capitalTimezone: "America/Havana",
    timezones: [{ id: "capital", label: "Havana (CST/CDT)", timezone: "America/Havana" }],
    politicalRegime: "República socialista de partido único",
    population: 11194449,
    languages: ["Espanhol"],
  },
  {
    id: "dm",
    continent: "america",
    name: "Dominica",
    capital: "Roseau",
    capitalLatitude: 15.3010,
    capitalLongitude: -61.3872,
    capitalTimezone: "America/Dominica",
    timezones: [{ id: "capital", label: "Roseau (AST)", timezone: "America/Dominica" }],
    politicalRegime: "República parlamentar",
    population: 72737,
    languages: ["Inglês"],
  },
  {
    id: "do",
    continent: "america",
    name: "República Dominicana",
    capital: "Santo Domingo",
    capitalLatitude: 18.4861,
    capitalLongitude: -69.9312,
    capitalTimezone: "America/Santo_Domingo",
    timezones: [{ id: "capital", label: "Santo Domingo (AST)", timezone: "America/Santo_Domingo" }],
    politicalRegime: "República presidencialista",
    population: 11228630,
    languages: ["Espanhol"],
  },
  {
    id: "ec",
    continent: "america",
    name: "Equador",
    capital: "Quito",
    capitalLatitude: -0.1807,
    capitalLongitude: -78.4678,
    capitalTimezone: "America/Guayaquil",
    timezones: [
      { id: "capital", label: "Quito (ECT)", timezone: "America/Guayaquil" },
      { id: "galapagos", label: "Galápagos (GALT)", timezone: "Pacific/Galapagos" },
    ],
    politicalRegime: "República presidencialista",
    population: 18190484,
    languages: ["Espanhol"],
  },
  {
    id: "sv",
    continent: "america",
    name: "El Salvador",
    capital: "San Salvador",
    capitalLatitude: 13.6929,
    capitalLongitude: -89.2182,
    capitalTimezone: "America/El_Salvador",
    timezones: [{ id: "capital", label: "San Salvador (CST)", timezone: "America/El_Salvador" }],
    politicalRegime: "República presidencialista",
    population: 6314167,
    languages: ["Espanhol"],
  },
  {
    id: "us",
    continent: "america",
    name: "Estados Unidos",
    capital: "Washington, D.C.",
    capitalLatitude: 38.9072,
    capitalLongitude: -77.0369,
    capitalTimezone: "America/New_York",
    timezones: [
      { id: "capital", label: "Washington, D.C. (ET)", timezone: "America/New_York" },
      { id: "chicago", label: "Chicago (CT)", timezone: "America/Chicago" },
      { id: "denver", label: "Denver (MT)", timezone: "America/Denver" },
      { id: "los-angeles", label: "Los Angeles (PT)", timezone: "America/Los_Angeles" },
      { id: "anchorage", label: "Anchorage (AKT)", timezone: "America/Anchorage" },
      { id: "honolulu", label: "Honolulu (HST)", timezone: "Pacific/Honolulu" },
    ],
    politicalRegime: "República federal presidencialista",
    population: 340110988,
    languages: ["Inglês"],
  },
  {
    id: "gd",
    continent: "america",
    name: "Granada",
    capital: "Saint George's",
    capitalLatitude: 12.0564,
    capitalLongitude: -61.7485,
    capitalTimezone: "America/Grenada",
    timezones: [{ id: "capital", label: "Saint George's (AST)", timezone: "America/Grenada" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 125438,
    languages: ["Inglês"],
  },
  {
    id: "gt",
    continent: "america",
    name: "Guatemala",
    capital: "Cidade da Guatemala",
    capitalLatitude: 14.6349,
    capitalLongitude: -90.5069,
    capitalTimezone: "America/Guatemala",
    timezones: [{ id: "capital", label: "Cidade da Guatemala (CST)", timezone: "America/Guatemala" }],
    politicalRegime: "República presidencialista",
    population: 17608483,
    languages: ["Espanhol"],
  },
  {
    id: "gy",
    continent: "america",
    name: "Guiana",
    capital: "Georgetown",
    capitalLatitude: 6.8013,
    capitalLongitude: -58.1551,
    capitalTimezone: "America/Guyana",
    timezones: [{ id: "capital", label: "Georgetown (GYT)", timezone: "America/Guyana" }],
    politicalRegime: "República presidencialista",
    population: 808726,
    languages: ["Inglês"],
  },
  {
    id: "ht",
    continent: "america",
    name: "Haiti",
    capital: "Porto Príncipe",
    capitalLatitude: 18.5944,
    capitalLongitude: -72.3074,
    capitalTimezone: "America/Port-au-Prince",
    timezones: [{ id: "capital", label: "Porto Príncipe (EST/EDT)", timezone: "America/Port-au-Prince" }],
    politicalRegime: "República semipresidencialista",
    population: 11724763,
    languages: ["Francês", "Crioulo haitiano"],
  },
  {
    id: "hn",
    continent: "america",
    name: "Honduras",
    capital: "Tegucigalpa",
    capitalLatitude: 14.0818,
    capitalLongitude: -87.2068,
    capitalTimezone: "America/Tegucigalpa",
    timezones: [{ id: "capital", label: "Tegucigalpa (CST)", timezone: "America/Tegucigalpa" }],
    politicalRegime: "República presidencialista",
    population: 10278345,
    languages: ["Espanhol"],
  },
  {
    id: "jm",
    continent: "america",
    name: "Jamaica",
    capital: "Kingston",
    capitalLatitude: 18.0179,
    capitalLongitude: -76.8099,
    capitalTimezone: "America/Jamaica",
    timezones: [{ id: "capital", label: "Kingston (EST)", timezone: "America/Jamaica" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 2825544,
    languages: ["Inglês"],
  },
  {
    id: "mx",
    continent: "america",
    name: "México",
    capital: "Cidade do México",
    capitalLatitude: 19.4326,
    capitalLongitude: -99.1332,
    capitalTimezone: "America/Mexico_City",
    timezones: [
      { id: "capital", label: "Cidade do México (CST)", timezone: "America/Mexico_City" },
      { id: "tijuana", label: "Tijuana (PT)", timezone: "America/Tijuana" },
      { id: "chihuahua", label: "Chihuahua (MT)", timezone: "America/Chihuahua" },
    ],
    politicalRegime: "República federal presidencialista",
    population: 128901530,
    languages: ["Espanhol"],
  },
  {
    id: "ni",
    continent: "america",
    name: "Nicarágua",
    capital: "Manágua",
    capitalLatitude: 12.1364,
    capitalLongitude: -86.2514,
    capitalTimezone: "America/Managua",
    timezones: [{ id: "capital", label: "Manágua (CST)", timezone: "America/Managua" }],
    politicalRegime: "República presidencialista",
    population: 6948392,
    languages: ["Espanhol"],
  },
  {
    id: "pa",
    continent: "america",
    name: "Panamá",
    capital: "Cidade do Panamá",
    capitalLatitude: 8.9824,
    capitalLongitude: -79.5199,
    capitalTimezone: "America/Panama",
    timezones: [{ id: "capital", label: "Cidade do Panamá (EST)", timezone: "America/Panama" }],
    politicalRegime: "República presidencialista",
    population: 4381579,
    languages: ["Espanhol"],
  },
  {
    id: "py",
    continent: "america",
    name: "Paraguai",
    capital: "Assunção",
    capitalLatitude: -25.2637,
    capitalLongitude: -57.5759,
    capitalTimezone: "America/Asuncion",
    timezones: [{ id: "capital", label: "Assunção (PYT/PYST)", timezone: "America/Asuncion" }],
    politicalRegime: "República presidencialista",
    population: 6109644,
    languages: ["Espanhol", "Guarani"],
  },
  {
    id: "pe",
    continent: "america",
    name: "Peru",
    capital: "Lima",
    capitalLatitude: -12.0464,
    capitalLongitude: -77.0428,
    capitalTimezone: "America/Lima",
    timezones: [{ id: "capital", label: "Lima (PET)", timezone: "America/Lima" }],
    politicalRegime: "República presidencialista",
    population: 34049588,
    languages: ["Espanhol"],
  },
  {
    id: "kn",
    continent: "america",
    name: "São Cristóvão e Neves",
    capital: "Basseterre",
    capitalLatitude: 17.3026,
    capitalLongitude: -62.7177,
    capitalTimezone: "America/St_Kitts",
    timezones: [{ id: "capital", label: "Basseterre (AST)", timezone: "America/St_Kitts" }],
    politicalRegime: "Monarquia constitucional parlamentar federal",
    population: 47606,
    languages: ["Inglês"],
  },
  {
    id: "vc",
    continent: "america",
    name: "São Vicente e Granadinas",
    capital: "Kingstown",
    capitalLatitude: 13.1587,
    capitalLongitude: -61.2248,
    capitalTimezone: "America/St_Vincent",
    timezones: [{ id: "capital", label: "Kingstown (AST)", timezone: "America/St_Vincent" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 101145,
    languages: ["Inglês"],
  },
  {
    id: "lc",
    continent: "america",
    name: "Santa Lúcia",
    capital: "Castries",
    capitalLatitude: 14.0101,
    capitalLongitude: -60.9875,
    capitalTimezone: "America/St_Lucia",
    timezones: [{ id: "capital", label: "Castries (AST)", timezone: "America/St_Lucia" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 180251,
    languages: ["Inglês"],
  },
  {
    id: "sr",
    continent: "america",
    name: "Suriname",
    capital: "Paramaribo",
    capitalLatitude: 5.8520,
    capitalLongitude: -55.2038,
    capitalTimezone: "America/Paramaribo",
    timezones: [{ id: "capital", label: "Paramaribo (SRT)", timezone: "America/Paramaribo" }],
    politicalRegime: "República presidencialista",
    population: 618040,
    languages: ["Holandês"],
  },
  {
    id: "tt",
    continent: "america",
    name: "Trinidad e Tobago",
    capital: "Porto Espanha",
    capitalLatitude: 10.6596,
    capitalLongitude: -61.5087,
    capitalTimezone: "America/Port_of_Spain",
    timezones: [{ id: "capital", label: "Porto Espanha (AST)", timezone: "America/Port_of_Spain" }],
    politicalRegime: "República parlamentar",
    population: 1534937,
    languages: ["Inglês"],
  },
  {
    id: "uy",
    continent: "america",
    name: "Uruguai",
    capital: "Montevidéu",
    capitalLatitude: -34.9011,
    capitalLongitude: -56.1645,
    capitalTimezone: "America/Montevideo",
    timezones: [{ id: "capital", label: "Montevidéu (UYT)", timezone: "America/Montevideo" }],
    politicalRegime: "República presidencialista",
    population: 3423108,
    languages: ["Espanhol"],
  },
  {
    id: "ve",
    continent: "america",
    name: "Venezuela",
    capital: "Caracas",
    capitalLatitude: 10.4806,
    capitalLongitude: -66.9036,
    capitalTimezone: "America/Caracas",
    timezones: [{ id: "capital", label: "Caracas (VET)", timezone: "America/Caracas" }],
    politicalRegime: "República federal presidencialista",
    population: 28838499,
    languages: ["Espanhol"],
  },

  // ════════════════════════════════════════════
  // ÁSIA
  // ════════════════════════════════════════════
  {
    id: "af",
    continent: "asia",
    name: "Afeganistão",
    capital: "Cabul",
    capitalLatitude: 34.5553,
    capitalLongitude: 69.2075,
    capitalTimezone: "Asia/Kabul",
    timezones: [{ id: "capital", label: "Cabul (AFT)", timezone: "Asia/Kabul" }],
    politicalRegime: "Emirado islâmico",
    population: 41128771,
    languages: ["Dari", "Pashto"],
  },
  {
    id: "sa",
    continent: "asia",
    name: "Arábia Saudita",
    capital: "Riade",
    capitalLatitude: 24.7136,
    capitalLongitude: 46.6753,
    capitalTimezone: "Asia/Riyadh",
    timezones: [{ id: "capital", label: "Riade (AST)", timezone: "Asia/Riyadh" }],
    politicalRegime: "Monarquia absoluta",
    population: 36947025,
    languages: ["Árabe"],
  },
  {
    id: "am",
    continent: "asia",
    name: "Armênia",
    capital: "Erevã",
    capitalLatitude: 40.1792,
    capitalLongitude: 44.4991,
    capitalTimezone: "Asia/Yerevan",
    timezones: [{ id: "capital", label: "Erevã (AMT)", timezone: "Asia/Yerevan" }],
    politicalRegime: "República parlamentar",
    population: 2777970,
    languages: ["Armênio"],
  },
  {
    id: "az",
    continent: "asia",
    name: "Azerbaijão",
    capital: "Baku",
    capitalLatitude: 40.4093,
    capitalLongitude: 49.8671,
    capitalTimezone: "Asia/Baku",
    timezones: [{ id: "capital", label: "Baku (AZT)", timezone: "Asia/Baku" }],
    politicalRegime: "República presidencialista",
    population: 10145212,
    languages: ["Azerbaijano"],
  },
  {
    id: "bh",
    continent: "asia",
    name: "Barein",
    capital: "Manama",
    capitalLatitude: 26.2285,
    capitalLongitude: 50.5860,
    capitalTimezone: "Asia/Bahrain",
    timezones: [{ id: "capital", label: "Manama (AST)", timezone: "Asia/Bahrain" }],
    politicalRegime: "Monarquia constitucional",
    population: 1501635,
    languages: ["Árabe"],
    aliases: ["Bahrein", "Bahrain"],
  },
  {
    id: "bd",
    continent: "asia",
    name: "Bangladesh",
    capital: "Daca",
    capitalLatitude: 23.8103,
    capitalLongitude: 90.4125,
    capitalTimezone: "Asia/Dhaka",
    timezones: [{ id: "capital", label: "Daca (BST)", timezone: "Asia/Dhaka" }],
    politicalRegime: "República parlamentar",
    population: 171186372,
    languages: ["Bengali"],
  },
  {
    id: "bn",
    continent: "asia",
    name: "Brunei",
    capital: "Bandar Seri Begawan",
    capitalLatitude: 4.9431,
    capitalLongitude: 114.9425,
    capitalTimezone: "Asia/Brunei",
    timezones: [{ id: "capital", label: "Bandar Seri Begawan (BNT)", timezone: "Asia/Brunei" }],
    politicalRegime: "Monarquia absoluta",
    population: 449002,
    languages: ["Malaio"],
  },
  {
    id: "bt",
    continent: "asia",
    name: "Butão",
    capital: "Thimphu",
    capitalLatitude: 27.4728,
    capitalLongitude: 89.6393,
    capitalTimezone: "Asia/Thimphu",
    timezones: [{ id: "capital", label: "Thimphu (BTT)", timezone: "Asia/Thimphu" }],
    politicalRegime: "Monarquia constitucional",
    population: 787941,
    languages: ["Dzongkha"],
  },
  {
    id: "kh",
    continent: "asia",
    name: "Camboja",
    capital: "Phnom Penh",
    capitalLatitude: 11.5564,
    capitalLongitude: 104.9282,
    capitalTimezone: "Asia/Phnom_Penh",
    timezones: [{ id: "capital", label: "Phnom Penh (ICT)", timezone: "Asia/Phnom_Penh" }],
    politicalRegime: "Monarquia constitucional",
    population: 16767842,
    languages: ["Khmer"],
  },
  {
    id: "qa",
    continent: "asia",
    name: "Catar",
    capital: "Doha",
    capitalLatitude: 25.2854,
    capitalLongitude: 51.5310,
    capitalTimezone: "Asia/Qatar",
    timezones: [{ id: "capital", label: "Doha (AST)", timezone: "Asia/Qatar" }],
    politicalRegime: "Monarquia absoluta",
    population: 2695122,
    languages: ["Árabe"],
  },
  {
    id: "kz",
    continent: "asia",
    name: "Cazaquistão",
    capital: "Astana",
    capitalLatitude: 51.1605,
    capitalLongitude: 71.4704,
    capitalTimezone: "Asia/Almaty",
    timezones: [
      { id: "capital", label: "Astana (ALMT)", timezone: "Asia/Almaty" },
      { id: "aqtau", label: "Aqtau (AQTT)", timezone: "Asia/Aqtau" },
    ],
    politicalRegime: "República presidencialista",
    population: 19606633,
    languages: ["Cazaque", "Russo"],
  },
  {
    id: "cn",
    continent: "asia",
    name: "China",
    capital: "Pequim",
    capitalLatitude: 39.9042,
    capitalLongitude: 116.4074,
    capitalTimezone: "Asia/Shanghai",
    timezones: [{ id: "capital", label: "Pequim (CST)", timezone: "Asia/Shanghai" }],
    politicalRegime: "República socialista de partido único",
    population: 1409670000,
    languages: ["Mandarim"],
  },
  {
    id: "kp",
    continent: "asia",
    name: "Coreia do Norte",
    capital: "Pyongyang",
    capitalLatitude: 39.0392,
    capitalLongitude: 125.7625,
    capitalTimezone: "Asia/Pyongyang",
    timezones: [{ id: "capital", label: "Pyongyang (KST)", timezone: "Asia/Pyongyang" }],
    politicalRegime: "República socialista de partido único",
    population: 26160821,
    languages: ["Coreano"],
  },
  {
    id: "kr",
    continent: "asia",
    name: "Coreia do Sul",
    capital: "Seul",
    capitalLatitude: 37.5665,
    capitalLongitude: 126.9780,
    capitalTimezone: "Asia/Seoul",
    timezones: [{ id: "capital", label: "Seul (KST)", timezone: "Asia/Seoul" }],
    politicalRegime: "República presidencialista",
    population: 51744876,
    languages: ["Coreano"],
  },
  {
    id: "ae",
    continent: "asia",
    name: "Emirados Árabes Unidos",
    capital: "Abu Dhabi",
    capitalLatitude: 24.4539,
    capitalLongitude: 54.3773,
    capitalTimezone: "Asia/Dubai",
    timezones: [{ id: "capital", label: "Abu Dhabi (GST)", timezone: "Asia/Dubai" }],
    politicalRegime: "Monarquia constitucional federal",
    population: 9441129,
    languages: ["Árabe"],
  },
  {
    id: "ph",
    continent: "asia",
    name: "Filipinas",
    capital: "Manila",
    capitalLatitude: 14.5995,
    capitalLongitude: 120.9842,
    capitalTimezone: "Asia/Manila",
    timezones: [{ id: "capital", label: "Manila (PHT)", timezone: "Asia/Manila" }],
    politicalRegime: "República presidencialista",
    population: 115559009,
    languages: ["Filipino", "Inglês"],
  },
  {
    id: "ge",
    continent: "asia",
    name: "Geórgia",
    capital: "Tbilisi",
    capitalLatitude: 41.7151,
    capitalLongitude: 44.8271,
    capitalTimezone: "Asia/Tbilisi",
    timezones: [{ id: "capital", label: "Tbilisi (GET)", timezone: "Asia/Tbilisi" }],
    politicalRegime: "República parlamentar",
    population: 3728573,
    languages: ["Georgiano"],
  },
  {
    id: "hk",
    continent: "asia",
    name: "Hong Kong",
    capital: "Hong Kong",
    capitalLatitude: 22.3193,
    capitalLongitude: 114.1694,
    capitalTimezone: "Asia/Hong_Kong",
    timezones: [{ id: "capital", label: "Hong Kong (HKT)", timezone: "Asia/Hong_Kong" }],
    politicalRegime: "Região administrativa especial",
    population: 7501497,
    languages: ["Chinês", "Inglês"],
  },
  {
    id: "ye",
    continent: "asia",
    name: "Iêmen",
    capital: "Sanaa",
    capitalLatitude: 15.3694,
    capitalLongitude: 44.1910,
    capitalTimezone: "Asia/Aden",
    timezones: [{ id: "capital", label: "Sanaa (AST)", timezone: "Asia/Aden" }],
    politicalRegime: "República presidencialista",
    population: 33696614,
    languages: ["Árabe"],
  },
  {
    id: "in",
    continent: "asia",
    name: "Índia",
    capital: "Nova Délhi",
    capitalLatitude: 28.6139,
    capitalLongitude: 77.2090,
    capitalTimezone: "Asia/Kolkata",
    timezones: [{ id: "capital", label: "Nova Délhi (IST)", timezone: "Asia/Kolkata" }],
    politicalRegime: "República federal parlamentar",
    population: 1438069596,
    languages: ["Hindi", "Inglês e idiomas regionais"],
  },
  {
    id: "id",
    continent: "asia",
    name: "Indonésia",
    capital: "Jacarta",
    capitalLatitude: -6.2088,
    capitalLongitude: 106.8456,
    capitalTimezone: "Asia/Jakarta",
    timezones: [
      { id: "capital", label: "Jacarta (WIB)", timezone: "Asia/Jakarta" },
      { id: "makassar", label: "Makassar (WITA)", timezone: "Asia/Makassar" },
      { id: "jayapura", label: "Jayapura (WIT)", timezone: "Asia/Jayapura" },
    ],
    politicalRegime: "República presidencialista",
    population: 277534122,
    languages: ["Indonésio"],
  },
  {
    id: "ir",
    continent: "asia",
    name: "Irã",
    capital: "Teerã",
    capitalLatitude: 35.6892,
    capitalLongitude: 51.3890,
    capitalTimezone: "Asia/Tehran",
    timezones: [{ id: "capital", label: "Teerã (IRST/IRDT)", timezone: "Asia/Tehran" }],
    politicalRegime: "República islâmica teocrática",
    population: 87923432,
    languages: ["Persa"],
  },
  {
    id: "iq",
    continent: "asia",
    name: "Iraque",
    capital: "Bagdá",
    capitalLatitude: 33.3152,
    capitalLongitude: 44.3661,
    capitalTimezone: "Asia/Baghdad",
    timezones: [{ id: "capital", label: "Bagdá (AST)", timezone: "Asia/Baghdad" }],
    politicalRegime: "República parlamentar federal",
    population: 44496122,
    languages: ["Árabe", "Curdo"],
  },
  {
    id: "il",
    continent: "asia",
    name: "Israel",
    capital: "Jerusalém",
    capitalLatitude: 31.7683,
    capitalLongitude: 35.2137,
    capitalTimezone: "Asia/Jerusalem",
    timezones: [{ id: "capital", label: "Jerusalém (IST/IDT)", timezone: "Asia/Jerusalem" }],
    politicalRegime: "República parlamentar",
    population: 9174520,
    languages: ["Hebraico", "Árabe"],
  },
  {
    id: "jp",
    continent: "asia",
    name: "Japão",
    capital: "Tóquio",
    capitalLatitude: 35.6762,
    capitalLongitude: 139.6503,
    capitalTimezone: "Asia/Tokyo",
    timezones: [{ id: "capital", label: "Tóquio (JST)", timezone: "Asia/Tokyo" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 123753041,
    languages: ["Japonês"],
  },
  {
    id: "jo",
    continent: "asia",
    name: "Jordânia",
    capital: "Amã",
    capitalLatitude: 31.9454,
    capitalLongitude: 35.9284,
    capitalTimezone: "Asia/Amman",
    timezones: [{ id: "capital", label: "Amã (EET/EEST)", timezone: "Asia/Amman" }],
    politicalRegime: "Monarquia constitucional",
    population: 11580936,
    languages: ["Árabe"],
  },
  {
    id: "kw",
    continent: "asia",
    name: "Kuwait",
    capital: "Cidade do Kuwait",
    capitalLatitude: 29.3759,
    capitalLongitude: 47.9774,
    capitalTimezone: "Asia/Kuwait",
    timezones: [{ id: "capital", label: "Cidade do Kuwait (AST)", timezone: "Asia/Kuwait" }],
    politicalRegime: "Monarquia constitucional",
    population: 4310108,
    languages: ["Árabe"],
  },
  {
    id: "kg",
    continent: "asia",
    name: "Quirguistão",
    capital: "Bishkek",
    capitalLatitude: 42.8746,
    capitalLongitude: 74.5698,
    capitalTimezone: "Asia/Bishkek",
    timezones: [{ id: "capital", label: "Bishkek (KGT)", timezone: "Asia/Bishkek" }],
    politicalRegime: "República presidencialista",
    population: 6974900,
    languages: ["Quirguiz", "Russo"],
  },
  {
    id: "lb",
    continent: "asia",
    name: "Líbano",
    capital: "Beirute",
    capitalLatitude: 33.8938,
    capitalLongitude: 35.5018,
    capitalTimezone: "Asia/Beirut",
    timezones: [{ id: "capital", label: "Beirute (EET/EEST)", timezone: "Asia/Beirut" }],
    politicalRegime: "República parlamentar",
    population: 5489739,
    languages: ["Árabe"],
  },
  {
    id: "my",
    continent: "asia",
    name: "Malásia",
    capital: "Kuala Lumpur",
    capitalLatitude: 3.1390,
    capitalLongitude: 101.6869,
    capitalTimezone: "Asia/Kuala_Lumpur",
    timezones: [{ id: "capital", label: "Kuala Lumpur (MYT)", timezone: "Asia/Kuala_Lumpur" }],
    politicalRegime: "Monarquia constitucional federal",
    population: 33938221,
    languages: ["Malaio"],
  },
  {
    id: "mv",
    continent: "asia",
    name: "Maldivas",
    capital: "Malé",
    capitalLatitude: 4.1755,
    capitalLongitude: 73.5093,
    capitalTimezone: "Indian/Maldives",
    timezones: [{ id: "capital", label: "Malé (MVT)", timezone: "Indian/Maldives" }],
    politicalRegime: "República presidencialista",
    population: 521457,
    languages: ["Maldiviano"],
  },
  {
    id: "mm",
    continent: "asia",
    name: "Mianmar",
    capital: "Naypyidaw",
    capitalLatitude: 19.7633,
    capitalLongitude: 96.0785,
    capitalTimezone: "Asia/Yangon",
    timezones: [{ id: "capital", label: "Naypyidaw (MMT)", timezone: "Asia/Yangon" }],
    politicalRegime: "Junta militar",
    population: 54179306,
    languages: ["Birmanês"],
  },
  {
    id: "mn",
    continent: "asia",
    name: "Mongólia",
    capital: "Ulaanbaatar",
    capitalLatitude: 47.8864,
    capitalLongitude: 106.9057,
    capitalTimezone: "Asia/Ulaanbaatar",
    timezones: [{ id: "capital", label: "Ulaanbaatar (ULAT)", timezone: "Asia/Ulaanbaatar" }],
    politicalRegime: "República parlamentar",
    population: 3447157,
    languages: ["Mongol"],
  },
  {
    id: "np",
    continent: "asia",
    name: "Nepal",
    capital: "Catmandu",
    capitalLatitude: 27.7172,
    capitalLongitude: 85.3240,
    capitalTimezone: "Asia/Kathmandu",
    timezones: [{ id: "capital", label: "Catmandu (NPT)", timezone: "Asia/Kathmandu" }],
    politicalRegime: "República parlamentar federal",
    population: 30896590,
    languages: ["Nepalês"],
  },
  {
    id: "om",
    continent: "asia",
    name: "Omã",
    capital: "Mascate",
    capitalLatitude: 23.5880,
    capitalLongitude: 58.3829,
    capitalTimezone: "Asia/Muscat",
    timezones: [{ id: "capital", label: "Mascate (GST)", timezone: "Asia/Muscat" }],
    politicalRegime: "Monarquia absoluta",
    population: 4644384,
    languages: ["Árabe"],
  },
  {
    id: "pk",
    continent: "asia",
    name: "Paquistão",
    capital: "Islamabad",
    capitalLatitude: 33.6844,
    capitalLongitude: 73.0479,
    capitalTimezone: "Asia/Karachi",
    timezones: [{ id: "capital", label: "Islamabad (PKT)", timezone: "Asia/Karachi" }],
    politicalRegime: "República parlamentar federal",
    population: 231402117,
    languages: ["Urdu", "Inglês"],
  },
  {
    id: "ru",
    continent: "asia",
    name: "Rússia",
    capital: "Moscou",
    capitalLatitude: 55.7558,
    capitalLongitude: 37.6173,
    capitalTimezone: "Europe/Moscow",
    timezones: [
      { id: "capital", label: "Moscou (MSK)", timezone: "Europe/Moscow" },
      { id: "yekaterinburg", label: "Ecaterimburgo (YEKT)", timezone: "Asia/Yekaterinburg" },
      { id: "vladivostok", label: "Vladivostok (VLAT)", timezone: "Asia/Vladivostok" },
      { id: "kamchatka", label: "Kamchatka (PETT)", timezone: "Asia/Kamchatka" },
    ],
    politicalRegime: "República federal semipresidencialista",
    population: 144236933,
    languages: ["Russo"],
    aliases: ["Federação da Rússia", "Federação Russa"],
  },
  {
    id: "sg",
    continent: "asia",
    name: "Singapura",
    capital: "Singapura",
    capitalLatitude: 1.3521,
    capitalLongitude: 103.8198,
    capitalTimezone: "Asia/Singapore",
    timezones: [{ id: "capital", label: "Singapura (SGT)", timezone: "Asia/Singapore" }],
    politicalRegime: "República parlamentar",
    population: 6036900,
    languages: ["Inglês", "Mandarim", "Malaio", "Tâmil"],
  },
  {
    id: "sy",
    continent: "asia",
    name: "Síria",
    capital: "Damasco",
    capitalLatitude: 33.5138,
    capitalLongitude: 36.2765,
    capitalTimezone: "Asia/Damascus",
    timezones: [{ id: "capital", label: "Damasco (EET/EEST)", timezone: "Asia/Damascus" }],
    politicalRegime: "República presidencialista",
    population: 22125249,
    languages: ["Árabe"],
  },
  {
    id: "lk",
    continent: "asia",
    name: "Sri Lanka",
    capital: "Sri Jayawardenepura Kotte",
    capitalLatitude: 6.9271,
    capitalLongitude: 79.8612,
    capitalTimezone: "Asia/Colombo",
    timezones: [{ id: "capital", label: "Colombo (IST)", timezone: "Asia/Colombo" }],
    politicalRegime: "República semipresidencialista",
    population: 22156000,
    languages: ["Cingalês", "Tâmil"],
  },
  {
    id: "tj",
    continent: "asia",
    name: "Tajiquistão",
    capital: "Dushanbe",
    capitalLatitude: 38.5598,
    capitalLongitude: 68.7738,
    capitalTimezone: "Asia/Dushanbe",
    timezones: [{ id: "capital", label: "Dushanbe (TJT)", timezone: "Asia/Dushanbe" }],
    politicalRegime: "República presidencialista",
    population: 10077600,
    languages: ["Tadjique"],
  },
  {
    id: "tw",
    continent: "asia",
    name: "Taiwan",
    capital: "Taipei",
    capitalLatitude: 25.0330,
    capitalLongitude: 121.5654,
    capitalTimezone: "Asia/Taipei",
    timezones: [{ id: "capital", label: "Taipei (CST)", timezone: "Asia/Taipei" }],
    politicalRegime: "República semipresidencialista",
    population: 23894394,
    languages: ["Mandarim"],
  },
  {
    id: "th",
    continent: "asia",
    name: "Tailândia",
    capital: "Bangkok",
    capitalLatitude: 13.7563,
    capitalLongitude: 100.5018,
    capitalTimezone: "Asia/Bangkok",
    timezones: [{ id: "capital", label: "Bangkok (ICT)", timezone: "Asia/Bangkok" }],
    politicalRegime: "Monarquia constitucional",
    population: 71801279,
    languages: ["Tailandês"],
  },
  {
    id: "tl",
    continent: "asia",
    name: "Timor-Leste",
    capital: "Díli",
    capitalLatitude: -8.5569,
    capitalLongitude: 125.5603,
    capitalTimezone: "Asia/Dili",
    timezones: [{ id: "capital", label: "Díli (TLT)", timezone: "Asia/Dili" }],
    politicalRegime: "República semipresidencialista",
    population: 1360596,
    languages: ["Português", "Tétum"],
  },
  {
    id: "tm",
    continent: "asia",
    name: "Turcomenistão",
    capital: "Ashgabat",
    capitalLatitude: 37.9601,
    capitalLongitude: 58.3261,
    capitalTimezone: "Asia/Ashgabat",
    timezones: [{ id: "capital", label: "Ashgabat (TMT)", timezone: "Asia/Ashgabat" }],
    politicalRegime: "República presidencialista",
    population: 6430770,
    languages: ["Turcomeno"],
  },
  {
    id: "tr",
    continent: "asia",
    name: "Turquia",
    capital: "Ancara",
    capitalLatitude: 39.9334,
    capitalLongitude: 32.8597,
    capitalTimezone: "Europe/Istanbul",
    timezones: [{ id: "capital", label: "Ancara (TRT)", timezone: "Europe/Istanbul" }],
    politicalRegime: "República presidencialista",
    population: 85279553,
    languages: ["Turco"],
  },
  {
    id: "uz",
    continent: "asia",
    name: "Uzbequistão",
    capital: "Tashkent",
    capitalLatitude: 41.2995,
    capitalLongitude: 69.2401,
    capitalTimezone: "Asia/Tashkent",
    timezones: [{ id: "capital", label: "Tashkent (UZT)", timezone: "Asia/Tashkent" }],
    politicalRegime: "República presidencialista",
    population: 35163944,
    languages: ["Uzbeque"],
  },
  {
    id: "vn",
    continent: "asia",
    name: "Vietnã",
    capital: "Hanói",
    capitalLatitude: 21.0285,
    capitalLongitude: 105.8542,
    capitalTimezone: "Asia/Ho_Chi_Minh",
    timezones: [{ id: "capital", label: "Hanói (ICT)", timezone: "Asia/Ho_Chi_Minh" }],
    politicalRegime: "República socialista de partido único",
    population: 99460000,
    languages: ["Vietnamita"],
  },

  // ════════════════════════════════════════════
  // ÁFRICA
  // ════════════════════════════════════════════
  {
    id: "za",
    continent: "africa",
    name: "África do Sul",
    capital: "Pretória",
    capitalLatitude: -25.7479,
    capitalLongitude: 28.2293,
    capitalTimezone: "Africa/Johannesburg",
    timezones: [{ id: "capital", label: "Pretória (SAST)", timezone: "Africa/Johannesburg" }],
    politicalRegime: "República parlamentar",
    population: 62027503,
    languages: ["Zulu", "Xhosa", "Africâner", "Inglês"],
  },
  {
    id: "dz",
    continent: "africa",
    name: "Argélia",
    capital: "Argel",
    capitalLatitude: 36.7538,
    capitalLongitude: 3.0588,
    capitalTimezone: "Africa/Algiers",
    timezones: [{ id: "capital", label: "Argel (CET)", timezone: "Africa/Algiers" }],
    politicalRegime: "República presidencialista",
    population: 44903225,
    languages: ["Árabe", "Amazigh"],
  },
  {
    id: "ao",
    continent: "africa",
    name: "Angola",
    capital: "Luanda",
    capitalLatitude: -8.8390,
    capitalLongitude: 13.2894,
    capitalTimezone: "Africa/Luanda",
    timezones: [{ id: "capital", label: "Luanda (WAT)", timezone: "Africa/Luanda" }],
    politicalRegime: "República presidencialista",
    population: 35588987,
    languages: ["Português"],
  },
  {
    id: "bj",
    continent: "africa",
    name: "Benin",
    capital: "Porto-Novo",
    capitalLatitude: 6.4969,
    capitalLongitude: 2.6289,
    capitalTimezone: "Africa/Porto-Novo",
    timezones: [{ id: "capital", label: "Porto-Novo (WAT)", timezone: "Africa/Porto-Novo" }],
    politicalRegime: "República presidencialista",
    population: 13352864,
    languages: ["Francês"],
  },
  {
    id: "bw",
    continent: "africa",
    name: "Botsuana",
    capital: "Gaborone",
    capitalLatitude: -24.6282,
    capitalLongitude: 25.9231,
    capitalTimezone: "Africa/Gaborone",
    timezones: [{ id: "capital", label: "Gaborone (CAT)", timezone: "Africa/Gaborone" }],
    politicalRegime: "República parlamentar",
    population: 2630296,
    languages: ["Inglês", "Setswana"],
  },
  {
    id: "bf",
    continent: "africa",
    name: "Burkina Faso",
    capital: "Ouagadougou",
    capitalLatitude: 12.3714,
    capitalLongitude: -1.5197,
    capitalTimezone: "Africa/Ouagadougou",
    timezones: [{ id: "capital", label: "Ouagadougou (GMT)", timezone: "Africa/Ouagadougou" }],
    politicalRegime: "Junta militar",
    population: 22673762,
    languages: ["Francês"],
  },
  {
    id: "bi",
    continent: "africa",
    name: "Burundi",
    capital: "Gitega",
    capitalLatitude: -3.4264,
    capitalLongitude: 29.9246,
    capitalTimezone: "Africa/Bujumbura",
    timezones: [{ id: "capital", label: "Gitega (CAT)", timezone: "Africa/Bujumbura" }],
    politicalRegime: "República presidencialista",
    population: 13238559,
    languages: ["Kirundi", "Francês"],
  },
  {
    id: "cv",
    continent: "africa",
    name: "Cabo Verde",
    capital: "Praia",
    capitalLatitude: 14.9330,
    capitalLongitude: -23.5133,
    capitalTimezone: "Atlantic/Cape_Verde",
    timezones: [{ id: "capital", label: "Praia (CVT)", timezone: "Atlantic/Cape_Verde" }],
    politicalRegime: "República semipresidencialista",
    population: 598682,
    languages: ["Português"],
  },
  {
    id: "cm",
    continent: "africa",
    name: "Camarões",
    capital: "Yaoundé",
    capitalLatitude: 3.8480,
    capitalLongitude: 11.5021,
    capitalTimezone: "Africa/Douala",
    timezones: [{ id: "capital", label: "Yaoundé (WAT)", timezone: "Africa/Douala" }],
    politicalRegime: "República presidencialista",
    population: 28647293,
    languages: ["Francês", "Inglês"],
  },
  {
    id: "td",
    continent: "africa",
    name: "Chade",
    capital: "N'Djamena",
    capitalLatitude: 12.1348,
    capitalLongitude: 15.0557,
    capitalTimezone: "Africa/Ndjamena",
    timezones: [{ id: "capital", label: "N'Djamena (WAT)", timezone: "Africa/Ndjamena" }],
    politicalRegime: "República presidencialista",
    population: 18278568,
    languages: ["Francês", "Árabe"],
  },
  {
    id: "km",
    continent: "africa",
    name: "Comores",
    capital: "Moroni",
    capitalLatitude: -11.7022,
    capitalLongitude: 43.2551,
    capitalTimezone: "Indian/Comoro",
    timezones: [{ id: "capital", label: "Moroni (EAT)", timezone: "Indian/Comoro" }],
    politicalRegime: "República presidencialista federal",
    population: 836774,
    languages: ["Árabe", "Francês", "Comoriano"],
  },
  {
    id: "cg",
    continent: "africa",
    name: "Congo",
    capital: "Brazzaville",
    capitalLatitude: -4.2634,
    capitalLongitude: 15.2429,
    capitalTimezone: "Africa/Brazzaville",
    timezones: [{ id: "capital", label: "Brazzaville (WAT)", timezone: "Africa/Brazzaville" }],
    politicalRegime: "República presidencialista",
    population: 6106869,
    languages: ["Francês"],
  },
  {
    id: "cd",
    continent: "africa",
    name: "República Democrática do Congo",
    capital: "Kinshasa",
    capitalLatitude: -4.4419,
    capitalLongitude: 15.2663,
    capitalTimezone: "Africa/Kinshasa",
    timezones: [
      { id: "capital", label: "Kinshasa (WAT)", timezone: "Africa/Kinshasa" },
      { id: "lubumbashi", label: "Lubumbashi (CAT)", timezone: "Africa/Lubumbashi" },
    ],
    politicalRegime: "República semipresidencialista",
    population: 102262808,
    languages: ["Francês"],
  },
  {
    id: "ci",
    continent: "africa",
    name: "Costa do Marfim",
    capital: "Yamoussoukro",
    capitalLatitude: 6.8276,
    capitalLongitude: -5.2893,
    capitalTimezone: "Africa/Abidjan",
    timezones: [{ id: "capital", label: "Yamoussoukro (GMT)", timezone: "Africa/Abidjan" }],
    politicalRegime: "República presidencialista",
    population: 28713423,
    languages: ["Francês"],
  },
  {
    id: "dj",
    continent: "africa",
    name: "Djibouti",
    capital: "Djibouti",
    capitalLatitude: 11.5721,
    capitalLongitude: 43.1456,
    capitalTimezone: "Africa/Djibouti",
    timezones: [{ id: "capital", label: "Djibouti (EAT)", timezone: "Africa/Djibouti" }],
    politicalRegime: "República presidencialista",
    population: 1120849,
    languages: ["Francês", "Árabe"],
  },
  {
    id: "eg",
    continent: "africa",
    name: "Egito",
    capital: "Cairo",
    capitalLatitude: 30.0444,
    capitalLongitude: 31.2357,
    capitalTimezone: "Africa/Cairo",
    timezones: [{ id: "capital", label: "Cairo (EET)", timezone: "Africa/Cairo" }],
    politicalRegime: "República presidencialista",
    population: 109262178,
    languages: ["Árabe"],
  },
  {
    id: "er",
    continent: "africa",
    name: "Eritreia",
    capital: "Asmara",
    capitalLatitude: 15.3229,
    capitalLongitude: 38.9251,
    capitalTimezone: "Africa/Asmara",
    timezones: [{ id: "capital", label: "Asmara (EAT)", timezone: "Africa/Asmara" }],
    politicalRegime: "República presidencialista de partido único",
    population: 3748901,
    languages: ["Tigrínia", "Árabe"],
  },
  {
    id: "sz",
    continent: "africa",
    name: "Eswatini",
    capital: "Mbabane",
    capitalLatitude: -26.3054,
    capitalLongitude: 31.1367,
    capitalTimezone: "Africa/Mbabane",
    timezones: [{ id: "capital", label: "Mbabane (SAST)", timezone: "Africa/Mbabane" }],
    politicalRegime: "Monarquia absoluta",
    population: 1210822,
    languages: ["Suázi", "Inglês"],
  },
  {
    id: "et",
    continent: "africa",
    name: "Etiópia",
    capital: "Addis Abeba",
    capitalLatitude: 9.0250,
    capitalLongitude: 38.7469,
    capitalTimezone: "Africa/Addis_Ababa",
    timezones: [{ id: "capital", label: "Addis Abeba (EAT)", timezone: "Africa/Addis_Ababa" }],
    politicalRegime: "República parlamentar federal",
    population: 126527060,
    languages: ["Amárico"],
  },
  {
    id: "ga",
    continent: "africa",
    name: "Gabão",
    capital: "Libreville",
    capitalLatitude: 0.4162,
    capitalLongitude: 9.4673,
    capitalTimezone: "Africa/Libreville",
    timezones: [{ id: "capital", label: "Libreville (WAT)", timezone: "Africa/Libreville" }],
    politicalRegime: "República presidencialista",
    population: 2388992,
    languages: ["Francês"],
  },
  {
    id: "gm",
    continent: "africa",
    name: "Gâmbia",
    capital: "Banjul",
    capitalLatitude: 13.4549,
    capitalLongitude: -16.5790,
    capitalTimezone: "Africa/Banjul",
    timezones: [{ id: "capital", label: "Banjul (GMT)", timezone: "Africa/Banjul" }],
    politicalRegime: "República presidencialista",
    population: 2639916,
    languages: ["Inglês"],
  },
  {
    id: "gh",
    continent: "africa",
    name: "Gana",
    capital: "Acra",
    capitalLatitude: 5.6037,
    capitalLongitude: -0.1870,
    capitalTimezone: "Africa/Accra",
    timezones: [{ id: "capital", label: "Acra (GMT)", timezone: "Africa/Accra" }],
    politicalRegime: "República presidencialista",
    population: 33475870,
    languages: ["Inglês"],
  },
  {
    id: "gn",
    continent: "africa",
    name: "Guiné",
    capital: "Conacri",
    capitalLatitude: 9.6412,
    capitalLongitude: -13.5784,
    capitalTimezone: "Africa/Conakry",
    timezones: [{ id: "capital", label: "Conacri (GMT)", timezone: "Africa/Conakry" }],
    politicalRegime: "Junta militar",
    population: 13859341,
    languages: ["Francês"],
  },
  {
    id: "gw",
    continent: "africa",
    name: "Guiné-Bissau",
    capital: "Bissau",
    capitalLatitude: 11.8037,
    capitalLongitude: -15.1804,
    capitalTimezone: "Africa/Bissau",
    timezones: [{ id: "capital", label: "Bissau (GMT)", timezone: "Africa/Bissau" }],
    politicalRegime: "República semipresidencialista",
    population: 2105566,
    languages: ["Português"],
  },
  {
    id: "gq",
    continent: "africa",
    name: "Guiné Equatorial",
    capital: "Malabo",
    capitalLatitude: 3.7500,
    capitalLongitude: 8.7833,
    capitalTimezone: "Africa/Malabo",
    timezones: [{ id: "capital", label: "Malabo (WAT)", timezone: "Africa/Malabo" }],
    politicalRegime: "República presidencialista",
    population: 1714671,
    languages: ["Espanhol", "Francês", "Português"],
  },
  {
    id: "ke",
    continent: "africa",
    name: "Quênia",
    capital: "Nairóbi",
    capitalLatitude: -1.2921,
    capitalLongitude: 36.8219,
    capitalTimezone: "Africa/Nairobi",
    timezones: [{ id: "capital", label: "Nairóbi (EAT)", timezone: "Africa/Nairobi" }],
    politicalRegime: "República presidencialista",
    population: 55100586,
    languages: ["Suaíli", "Inglês"],
  },
  {
    id: "ls",
    continent: "africa",
    name: "Lesoto",
    capital: "Maseru",
    capitalLatitude: -29.3167,
    capitalLongitude: 27.4833,
    capitalTimezone: "Africa/Maseru",
    timezones: [{ id: "capital", label: "Maseru (SAST)", timezone: "Africa/Maseru" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 2330318,
    languages: ["Sesoto", "Inglês"],
  },
  {
    id: "lr",
    continent: "africa",
    name: "Libéria",
    capital: "Monróvia",
    capitalLatitude: 6.2907,
    capitalLongitude: -10.7605,
    capitalTimezone: "Africa/Monrovia",
    timezones: [{ id: "capital", label: "Monróvia (GMT)", timezone: "Africa/Monrovia" }],
    politicalRegime: "República presidencialista",
    population: 5358483,
    languages: ["Inglês"],
  },
  {
    id: "ly",
    continent: "africa",
    name: "Líbia",
    capital: "Trípoli",
    capitalLatitude: 32.8872,
    capitalLongitude: 13.1913,
    capitalTimezone: "Africa/Tripoli",
    timezones: [{ id: "capital", label: "Trípoli (EET)", timezone: "Africa/Tripoli" }],
    politicalRegime: "Governo de transição",
    population: 7137931,
    languages: ["Árabe"],
  },
  {
    id: "mg",
    continent: "africa",
    name: "Madagascar",
    capital: "Antananarivo",
    capitalLatitude: -18.8792,
    capitalLongitude: 47.5079,
    capitalTimezone: "Indian/Antananarivo",
    timezones: [{ id: "capital", label: "Antananarivo (EAT)", timezone: "Indian/Antananarivo" }],
    politicalRegime: "República semipresidencialista",
    population: 30325732,
    languages: ["Malgaxe", "Francês"],
  },
  {
    id: "mw",
    continent: "africa",
    name: "Malauí",
    capital: "Lilongwe",
    capitalLatitude: -13.9626,
    capitalLongitude: 33.7741,
    capitalTimezone: "Africa/Blantyre",
    timezones: [{ id: "capital", label: "Lilongwe (CAT)", timezone: "Africa/Blantyre" }],
    politicalRegime: "República presidencialista",
    population: 20405317,
    languages: ["Inglês", "Chichewa"],
  },
  {
    id: "ml",
    continent: "africa",
    name: "Mali",
    capital: "Bamako",
    capitalLatitude: 12.6392,
    capitalLongitude: -8.0029,
    capitalTimezone: "Africa/Bamako",
    timezones: [{ id: "capital", label: "Bamako (GMT)", timezone: "Africa/Bamako" }],
    politicalRegime: "Junta militar",
    population: 22593590,
    languages: ["Francês"],
  },
  {
    id: "ma",
    continent: "africa",
    name: "Marrocos",
    capital: "Rabat",
    capitalLatitude: 33.9716,
    capitalLongitude: -6.8498,
    capitalTimezone: "Africa/Casablanca",
    timezones: [{ id: "capital", label: "Rabat (WET/WEST)", timezone: "Africa/Casablanca" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 37457971,
    languages: ["Árabe", "Amazigh"],
  },
  {
    id: "mu",
    continent: "africa",
    name: "Maurício",
    capital: "Port Louis",
    capitalLatitude: -20.1609,
    capitalLongitude: 57.5012,
    capitalTimezone: "Indian/Mauritius",
    timezones: [{ id: "capital", label: "Port Louis (MUT)", timezone: "Indian/Mauritius" }],
    politicalRegime: "República parlamentar",
    population: 1265740,
    languages: ["Inglês", "Francês", "Crioulo mauriciano"],
  },
  {
    id: "mr",
    continent: "africa",
    name: "Mauritânia",
    capital: "Nouakchott",
    capitalLatitude: 18.0735,
    capitalLongitude: -15.9582,
    capitalTimezone: "Africa/Nouakchott",
    timezones: [{ id: "capital", label: "Nouakchott (GMT)", timezone: "Africa/Nouakchott" }],
    politicalRegime: "República presidencialista",
    population: 4736139,
    languages: ["Árabe"],
  },
  {
    id: "mz",
    continent: "africa",
    name: "Moçambique",
    capital: "Maputo",
    capitalLatitude: -25.9692,
    capitalLongitude: 32.5732,
    capitalTimezone: "Africa/Maputo",
    timezones: [{ id: "capital", label: "Maputo (CAT)", timezone: "Africa/Maputo" }],
    politicalRegime: "República presidencialista",
    population: 33897354,
    languages: ["Português"],
  },
  {
    id: "na",
    continent: "africa",
    name: "Namíbia",
    capital: "Windhoek",
    capitalLatitude: -22.5609,
    capitalLongitude: 17.0658,
    capitalTimezone: "Africa/Windhoek",
    timezones: [{ id: "capital", label: "Windhoek (CAT)", timezone: "Africa/Windhoek" }],
    politicalRegime: "República presidencialista",
    population: 2604172,
    languages: ["Inglês"],
  },
  {
    id: "ne",
    continent: "africa",
    name: "Niger",
    capital: "Niamey",
    capitalLatitude: 13.5127,
    capitalLongitude: 2.1128,
    capitalTimezone: "Africa/Niamey",
    timezones: [{ id: "capital", label: "Niamey (WAT)", timezone: "Africa/Niamey" }],
    politicalRegime: "Junta militar",
    population: 26207977,
    languages: ["Francês"],
  },
  {
    id: "ng",
    continent: "africa",
    name: "Nigéria",
    capital: "Abuja",
    capitalLatitude: 9.0765,
    capitalLongitude: 7.3986,
    capitalTimezone: "Africa/Lagos",
    timezones: [{ id: "capital", label: "Abuja (WAT)", timezone: "Africa/Lagos" }],
    politicalRegime: "República federal presidencialista",
    population: 223804632,
    languages: ["Inglês"],
  },
  {
    id: "cf",
    continent: "africa",
    name: "República Centro-Africana",
    capital: "Bangui",
    capitalLatitude: 4.3947,
    capitalLongitude: 18.5582,
    capitalTimezone: "Africa/Bangui",
    timezones: [{ id: "capital", label: "Bangui (WAT)", timezone: "Africa/Bangui" }],
    politicalRegime: "República presidencialista",
    population: 5742315,
    languages: ["Francês", "Sango"],
  },
  {
    id: "rw",
    continent: "africa",
    name: "Ruanda",
    capital: "Kigali",
    capitalLatitude: -1.9403,
    capitalLongitude: 29.8739,
    capitalTimezone: "Africa/Kigali",
    timezones: [{ id: "capital", label: "Kigali (CAT)", timezone: "Africa/Kigali" }],
    politicalRegime: "República presidencialista",
    population: 14094683,
    languages: ["Kinyarwanda", "Francês", "Inglês"],
  },
  {
    id: "st",
    continent: "africa",
    name: "São Tomé e Príncipe",
    capital: "São Tomé",
    capitalLatitude: 0.1864,
    capitalLongitude: 6.6131,
    capitalTimezone: "Africa/Sao_Tome",
    timezones: [{ id: "capital", label: "São Tomé (GMT)", timezone: "Africa/Sao_Tome" }],
    politicalRegime: "República semipresidencialista",
    population: 227380,
    languages: ["Português"],
  },
  {
    id: "sn",
    continent: "africa",
    name: "Senegal",
    capital: "Dakar",
    capitalLatitude: 14.7167,
    capitalLongitude: -17.4677,
    capitalTimezone: "Africa/Dakar",
    timezones: [{ id: "capital", label: "Dakar (GMT)", timezone: "Africa/Dakar" }],
    politicalRegime: "República presidencialista",
    population: 17763163,
    languages: ["Francês"],
  },
  {
    id: "sc",
    continent: "africa",
    name: "Seicheles",
    capital: "Victoria",
    capitalLatitude: -4.6191,
    capitalLongitude: 55.4513,
    capitalTimezone: "Indian/Mahe",
    timezones: [{ id: "capital", label: "Victoria (SCT)", timezone: "Indian/Mahe" }],
    politicalRegime: "República presidencialista",
    population: 119773,
    languages: ["Crioulo seichelense", "Francês", "Inglês"],
  },
  {
    id: "sl",
    continent: "africa",
    name: "Serra Leoa",
    capital: "Freetown",
    capitalLatitude: 8.4657,
    capitalLongitude: -13.2317,
    capitalTimezone: "Africa/Freetown",
    timezones: [{ id: "capital", label: "Freetown (GMT)", timezone: "Africa/Freetown" }],
    politicalRegime: "República presidencialista",
    population: 8605718,
    languages: ["Inglês"],
  },
  {
    id: "so",
    continent: "africa",
    name: "Somália",
    capital: "Mogadíscio",
    capitalLatitude: 2.0469,
    capitalLongitude: 45.3182,
    capitalTimezone: "Africa/Mogadishu",
    timezones: [{ id: "capital", label: "Mogadíscio (EAT)", timezone: "Africa/Mogadishu" }],
    politicalRegime: "República parlamentar federal",
    population: 18143378,
    languages: ["Somali", "Árabe"],
  },
  {
    id: "sd",
    continent: "africa",
    name: "Sudão",
    capital: "Cartum",
    capitalLatitude: 15.5007,
    capitalLongitude: 32.5599,
    capitalTimezone: "Africa/Khartoum",
    timezones: [{ id: "capital", label: "Cartum (CAT)", timezone: "Africa/Khartoum" }],
    politicalRegime: "Governo de transição",
    population: 48109006,
    languages: ["Árabe", "Inglês"],
  },
  {
    id: "ss",
    continent: "africa",
    name: "Sudão do Sul",
    capital: "Juba",
    capitalLatitude: 4.8594,
    capitalLongitude: 31.5713,
    capitalTimezone: "Africa/Juba",
    timezones: [{ id: "capital", label: "Juba (CAT)", timezone: "Africa/Juba" }],
    politicalRegime: "República presidencialista",
    population: 11088796,
    languages: ["Inglês"],
  },
  {
    id: "tz",
    continent: "africa",
    name: "Tanzânia",
    capital: "Dodoma",
    capitalLatitude: -6.1630,
    capitalLongitude: 35.7516,
    capitalTimezone: "Africa/Dar_es_Salaam",
    timezones: [{ id: "capital", label: "Dodoma (EAT)", timezone: "Africa/Dar_es_Salaam" }],
    politicalRegime: "República presidencialista",
    population: 65497748,
    languages: ["Suaíli", "Inglês"],
  },
  {
    id: "tg",
    continent: "africa",
    name: "Togo",
    capital: "Lomé",
    capitalLatitude: 6.1725,
    capitalLongitude: 1.2314,
    capitalTimezone: "Africa/Lome",
    timezones: [{ id: "capital", label: "Lomé (GMT)", timezone: "Africa/Lome" }],
    politicalRegime: "República presidencialista",
    population: 8848699,
    languages: ["Francês"],
  },
  {
    id: "tn",
    continent: "africa",
    name: "Tunísia",
    capital: "Túnis",
    capitalLatitude: 36.8065,
    capitalLongitude: 10.1815,
    capitalTimezone: "Africa/Tunis",
    timezones: [{ id: "capital", label: "Túnis (CET)", timezone: "Africa/Tunis" }],
    politicalRegime: "República presidencialista",
    population: 12458223,
    languages: ["Árabe"],
  },
  {
    id: "ug",
    continent: "africa",
    name: "Uganda",
    capital: "Kampala",
    capitalLatitude: 0.3476,
    capitalLongitude: 32.5825,
    capitalTimezone: "Africa/Kampala",
    timezones: [{ id: "capital", label: "Kampala (EAT)", timezone: "Africa/Kampala" }],
    politicalRegime: "República presidencialista",
    population: 48582334,
    languages: ["Inglês", "Suaíli"],
  },
  {
    id: "zm",
    continent: "africa",
    name: "Zâmbia",
    capital: "Lusaka",
    capitalLatitude: -15.3875,
    capitalLongitude: 28.3228,
    capitalTimezone: "Africa/Lusaka",
    timezones: [{ id: "capital", label: "Lusaka (CAT)", timezone: "Africa/Lusaka" }],
    politicalRegime: "República presidencialista",
    population: 20569737,
    languages: ["Inglês"],
  },
  {
    id: "zw",
    continent: "africa",
    name: "Zimbábue",
    capital: "Harare",
    capitalLatitude: -17.8252,
    capitalLongitude: 31.0335,
    capitalTimezone: "Africa/Harare",
    timezones: [{ id: "capital", label: "Harare (CAT)", timezone: "Africa/Harare" }],
    politicalRegime: "República presidencialista",
    population: 16665409,
    languages: ["Inglês", "Shona", "Ndebele"],
  },

  // ════════════════════════════════════════════
  // ANTÁRTIDA (estações de pesquisa)
  // ════════════════════════════════════════════
  {
    id: "aq-mcmurdo",
    continent: "antarctica",
    name: "Estação McMurdo",
    capital: "McMurdo",
    capitalLatitude: -77.8419,
    capitalLongitude: 166.6863,
    capitalTimezone: "Antarctica/McMurdo",
    timezones: [{ id: "capital", label: "McMurdo (NZST/NZDT)", timezone: "Antarctica/McMurdo" }],
    politicalRegime: "Base de pesquisa (EUA)",
    population: null,
    languages: ["Inglês"],
  },
  {
    id: "aq-palmer",
    continent: "antarctica",
    name: "Estação Palmer",
    capital: "Palmer",
    capitalLatitude: -64.7743,
    capitalLongitude: -64.0538,
    capitalTimezone: "Antarctica/Palmer",
    timezones: [{ id: "capital", label: "Palmer (CLT/CLST)", timezone: "Antarctica/Palmer" }],
    politicalRegime: "Base de pesquisa (EUA)",
    population: null,
    languages: ["Inglês"],
  },
  {
    id: "aq-rothera",
    continent: "antarctica",
    name: "Estação Rothera",
    capital: "Rothera",
    capitalLatitude: -67.5675,
    capitalLongitude: -68.1250,
    capitalTimezone: "Antarctica/Rothera",
    timezones: [{ id: "capital", label: "Rothera (-03)", timezone: "Antarctica/Rothera" }],
    politicalRegime: "Base de pesquisa (Reino Unido)",
    population: null,
    languages: ["Inglês"],
  },
  {
    id: "aq-comandante-ferraz",
    continent: "antarctica",
    name: "Estação Comandante Ferraz",
    capital: "Comandante Ferraz",
    capitalLatitude: -62.0849,
    capitalLongitude: -58.3911,
    capitalTimezone: "Antarctica/Palmer",
    timezones: [{ id: "capital", label: "Comandante Ferraz (-03)", timezone: "Antarctica/Palmer" }],
    politicalRegime: "Base de pesquisa (Brasil)",
    population: null,
    languages: ["Português"],
  },

  // ════════════════════════════════════════════
  // EUROPA
  // ════════════════════════════════════════════
  {
    id: "al",
    continent: "europe",
    name: "Albânia",
    capital: "Tirana",
    capitalLatitude: 41.3275,
    capitalLongitude: 19.8187,
    capitalTimezone: "Europe/Tirane",
    timezones: [{ id: "capital", label: "Tirana (CET/CEST)", timezone: "Europe/Tirane" }],
    politicalRegime: "República parlamentar",
    population: 2761785,
    languages: ["Albanês"],
  },
  {
    id: "de",
    continent: "europe",
    name: "Alemanha",
    capital: "Berlim",
    capitalLatitude: 52.5200,
    capitalLongitude: 13.4050,
    capitalTimezone: "Europe/Berlin",
    timezones: [{ id: "capital", label: "Berlim (CET/CEST)", timezone: "Europe/Berlin" }],
    politicalRegime: "República federal parlamentar",
    population: 84552242,
    languages: ["Alemão"],
  },
  {
    id: "ad",
    continent: "europe",
    name: "Andorra",
    capital: "Andorra-a-Velha",
    capitalLatitude: 42.5063,
    capitalLongitude: 1.5218,
    capitalTimezone: "Europe/Andorra",
    timezones: [{ id: "capital", label: "Andorra-a-Velha (CET/CEST)", timezone: "Europe/Andorra" }],
    politicalRegime: "Coprincipado parlamentar",
    population: 80088,
    languages: ["Catalão"],
  },
  {
    id: "at",
    continent: "europe",
    name: "Áustria",
    capital: "Viena",
    capitalLatitude: 48.2082,
    capitalLongitude: 16.3738,
    capitalTimezone: "Europe/Vienna",
    timezones: [{ id: "capital", label: "Viena (CET/CEST)", timezone: "Europe/Vienna" }],
    politicalRegime: "República federal parlamentar",
    population: 9120813,
    languages: ["Alemão"],
  },
  {
    id: "by",
    continent: "europe",
    name: "Belarus",
    capital: "Minsk",
    capitalLatitude: 53.9045,
    capitalLongitude: 27.5615,
    capitalTimezone: "Europe/Minsk",
    timezones: [{ id: "capital", label: "Minsk (MSK)", timezone: "Europe/Minsk" }],
    politicalRegime: "República presidencialista",
    population: 9498238,
    languages: ["Bielorrusso", "Russo"],
  },
  {
    id: "be",
    continent: "europe",
    name: "Bélgica",
    capital: "Bruxelas",
    capitalLatitude: 50.8503,
    capitalLongitude: 4.3517,
    capitalTimezone: "Europe/Brussels",
    timezones: [{ id: "capital", label: "Bruxelas (CET/CEST)", timezone: "Europe/Brussels" }],
    politicalRegime: "Monarquia constitucional federal parlamentar",
    population: 11686140,
    languages: ["Holandês", "Francês", "Alemão"],
  },
  {
    id: "ba",
    continent: "europe",
    name: "Bósnia e Herzegovina",
    capital: "Sarajevo",
    capitalLatitude: 43.8564,
    capitalLongitude: 18.4131,
    capitalTimezone: "Europe/Sarajevo",
    timezones: [{ id: "capital", label: "Sarajevo (CET/CEST)", timezone: "Europe/Sarajevo" }],
    politicalRegime: "República parlamentar federal",
    population: 3210847,
    languages: ["Bósnio", "Sérvio", "Croata"],
  },
  {
    id: "bg",
    continent: "europe",
    name: "Bulgária",
    capital: "Sófia",
    capitalLatitude: 42.6977,
    capitalLongitude: 23.3219,
    capitalTimezone: "Europe/Sofia",
    timezones: [{ id: "capital", label: "Sófia (EET/EEST)", timezone: "Europe/Sofia" }],
    politicalRegime: "República parlamentar",
    population: 6447710,
    languages: ["Búlgaro"],
  },
  {
    id: "cy",
    continent: "europe",
    name: "Chipre",
    capital: "Nicósia",
    capitalLatitude: 35.1856,
    capitalLongitude: 33.3823,
    capitalTimezone: "Asia/Nicosia",
    timezones: [{ id: "capital", label: "Nicósia (EET/EEST)", timezone: "Asia/Nicosia" }],
    politicalRegime: "República presidencialista",
    population: 1260138,
    languages: ["Grego", "Turco"],
  },
  {
    id: "hr",
    continent: "europe",
    name: "Croácia",
    capital: "Zagreb",
    capitalLatitude: 45.8150,
    capitalLongitude: 15.9819,
    capitalTimezone: "Europe/Zagreb",
    timezones: [{ id: "capital", label: "Zagreb (CET/CEST)", timezone: "Europe/Zagreb" }],
    politicalRegime: "República parlamentar",
    population: 3855600,
    languages: ["Croata"],
  },
  {
    id: "dk",
    continent: "europe",
    name: "Dinamarca",
    capital: "Copenhague",
    capitalLatitude: 55.6761,
    capitalLongitude: 12.5683,
    capitalTimezone: "Europe/Copenhagen",
    timezones: [{ id: "capital", label: "Copenhague (CET/CEST)", timezone: "Europe/Copenhagen" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 5932654,
    languages: ["Dinamarquês"],
  },
  {
    id: "sk",
    continent: "europe",
    name: "Eslováquia",
    capital: "Bratislava",
    capitalLatitude: 48.1486,
    capitalLongitude: 17.1077,
    capitalTimezone: "Europe/Bratislava",
    timezones: [{ id: "capital", label: "Bratislava (CET/CEST)", timezone: "Europe/Bratislava" }],
    politicalRegime: "República parlamentar",
    population: 5460185,
    languages: ["Eslovaco"],
  },
  {
    id: "si",
    continent: "europe",
    name: "Eslovênia",
    capital: "Liubliana",
    capitalLatitude: 46.0569,
    capitalLongitude: 14.5058,
    capitalTimezone: "Europe/Ljubljana",
    timezones: [{ id: "capital", label: "Liubliana (CET/CEST)", timezone: "Europe/Ljubljana" }],
    politicalRegime: "República parlamentar",
    population: 2116792,
    languages: ["Esloveno"],
  },
  {
    id: "es",
    continent: "europe",
    name: "Espanha",
    capital: "Madri",
    capitalLatitude: 40.4168,
    capitalLongitude: -3.7038,
    capitalTimezone: "Europe/Madrid",
    timezones: [
      { id: "capital", label: "Madri (CET/CEST)", timezone: "Europe/Madrid" },
      { id: "canarias", label: "Canárias (WET/WEST)", timezone: "Atlantic/Canary" },
    ],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 48059777,
    languages: ["Espanhol"],
  },
  {
    id: "ee",
    continent: "europe",
    name: "Estônia",
    capital: "Tallinn",
    capitalLatitude: 59.4370,
    capitalLongitude: 24.7536,
    capitalTimezone: "Europe/Tallinn",
    timezones: [{ id: "capital", label: "Tallinn (EET/EEST)", timezone: "Europe/Tallinn" }],
    politicalRegime: "República parlamentar",
    population: 1373101,
    languages: ["Estoniano"],
  },
  {
    id: "fi",
    continent: "europe",
    name: "Finlândia",
    capital: "Helsinque",
    capitalLatitude: 60.1699,
    capitalLongitude: 24.9384,
    capitalTimezone: "Europe/Helsinki",
    timezones: [{ id: "capital", label: "Helsinque (EET/EEST)", timezone: "Europe/Helsinki" }],
    politicalRegime: "República parlamentar",
    population: 5614571,
    languages: ["Finlandês", "Sueco"],
  },
  {
    id: "fr",
    continent: "europe",
    name: "França",
    capital: "Paris",
    capitalLatitude: 48.8566,
    capitalLongitude: 2.3522,
    capitalTimezone: "Europe/Paris",
    timezones: [{ id: "capital", label: "Paris (CET/CEST)", timezone: "Europe/Paris" }],
    politicalRegime: "República semipresidencialista",
    population: 68373433,
    languages: ["Francês"],
  },
  {
    id: "gr",
    continent: "europe",
    name: "Grécia",
    capital: "Atenas",
    capitalLatitude: 37.9838,
    capitalLongitude: 23.7275,
    capitalTimezone: "Europe/Athens",
    timezones: [{ id: "capital", label: "Atenas (EET/EEST)", timezone: "Europe/Athens" }],
    politicalRegime: "República parlamentar",
    population: 10341277,
    languages: ["Grego"],
  },
  {
    id: "nl",
    continent: "europe",
    name: "Países Baixos",
    capital: "Amsterdã",
    capitalLatitude: 52.3676,
    capitalLongitude: 4.9041,
    capitalTimezone: "Europe/Amsterdam",
    timezones: [{ id: "capital", label: "Amsterdã (CET/CEST)", timezone: "Europe/Amsterdam" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 17811291,
    languages: ["Holandês"],
    aliases: ["Holanda"],
  },
  {
    id: "hu",
    continent: "europe",
    name: "Hungria",
    capital: "Budapeste",
    capitalLatitude: 47.4979,
    capitalLongitude: 19.0402,
    capitalTimezone: "Europe/Budapest",
    timezones: [{ id: "capital", label: "Budapeste (CET/CEST)", timezone: "Europe/Budapest" }],
    politicalRegime: "República parlamentar",
    population: 9597085,
    languages: ["Húngaro"],
  },
  {
    id: "ie",
    continent: "europe",
    name: "Irlanda",
    capital: "Dublin",
    capitalLatitude: 53.3498,
    capitalLongitude: -6.2603,
    capitalTimezone: "Europe/Dublin",
    timezones: [{ id: "capital", label: "Dublin (GMT/IST)", timezone: "Europe/Dublin" }],
    politicalRegime: "República parlamentar",
    population: 5194336,
    languages: ["Inglês", "Irlandês"],
  },
  {
    id: "is",
    continent: "europe",
    name: "Islândia",
    capital: "Reykjavik",
    capitalLatitude: 64.1466,
    capitalLongitude: -21.9426,
    capitalTimezone: "Atlantic/Reykjavik",
    timezones: [{ id: "capital", label: "Reykjavik (GMT)", timezone: "Atlantic/Reykjavik" }],
    politicalRegime: "República parlamentar",
    population: 393600,
    languages: ["Islandês"],
  },
  {
    id: "it",
    continent: "europe",
    name: "Itália",
    capital: "Roma",
    capitalLatitude: 41.9028,
    capitalLongitude: 12.4964,
    capitalTimezone: "Europe/Rome",
    timezones: [{ id: "capital", label: "Roma (CET/CEST)", timezone: "Europe/Rome" }],
    politicalRegime: "República parlamentar",
    population: 58870762,
    languages: ["Italiano"],
  },
  {
    id: "lv",
    continent: "europe",
    name: "Letônia",
    capital: "Riga",
    capitalLatitude: 56.9496,
    capitalLongitude: 24.1052,
    capitalTimezone: "Europe/Riga",
    timezones: [{ id: "capital", label: "Riga (EET/EEST)", timezone: "Europe/Riga" }],
    politicalRegime: "República parlamentar",
    population: 1830211,
    languages: ["Letão"],
  },
  {
    id: "li",
    continent: "europe",
    name: "Liechtenstein",
    capital: "Vaduz",
    capitalLatitude: 47.1410,
    capitalLongitude: 9.5209,
    capitalTimezone: "Europe/Vaduz",
    timezones: [{ id: "capital", label: "Vaduz (CET/CEST)", timezone: "Europe/Vaduz" }],
    politicalRegime: "Monarquia constitucional",
    population: 39870,
    languages: ["Alemão"],
  },
  {
    id: "lt",
    continent: "europe",
    name: "Lituânia",
    capital: "Vilnius",
    capitalLatitude: 54.6872,
    capitalLongitude: 25.2797,
    capitalTimezone: "Europe/Vilnius",
    timezones: [{ id: "capital", label: "Vilnius (EET/EEST)", timezone: "Europe/Vilnius" }],
    politicalRegime: "República semipresidencialista",
    population: 2860002,
    languages: ["Lituano"],
  },
  {
    id: "lu",
    continent: "europe",
    name: "Luxemburgo",
    capital: "Luxemburgo",
    capitalLatitude: 49.6117,
    capitalLongitude: 6.1300,
    capitalTimezone: "Europe/Luxembourg",
    timezones: [{ id: "capital", label: "Luxemburgo (CET/CEST)", timezone: "Europe/Luxembourg" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 672050,
    languages: ["Luxemburguês", "Francês", "Alemão"],
  },
  {
    id: "mk",
    continent: "europe",
    name: "Macedônia do Norte",
    capital: "Skopje",
    capitalLatitude: 41.9973,
    capitalLongitude: 21.4280,
    capitalTimezone: "Europe/Skopje",
    timezones: [{ id: "capital", label: "Skopje (CET/CEST)", timezone: "Europe/Skopje" }],
    politicalRegime: "República parlamentar",
    population: 1832696,
    languages: ["Macedônio"],
  },
  {
    id: "mt",
    continent: "europe",
    name: "Malta",
    capital: "Valletta",
    capitalLatitude: 35.8997,
    capitalLongitude: 14.5147,
    capitalTimezone: "Europe/Malta",
    timezones: [{ id: "capital", label: "Valletta (CET/CEST)", timezone: "Europe/Malta" }],
    politicalRegime: "República parlamentar",
    population: 542051,
    languages: ["Maltês", "Inglês"],
  },
  {
    id: "md",
    continent: "europe",
    name: "Moldávia",
    capital: "Chișinău",
    capitalLatitude: 47.0105,
    capitalLongitude: 28.8638,
    capitalTimezone: "Europe/Chisinau",
    timezones: [{ id: "capital", label: "Chișinău (EET/EEST)", timezone: "Europe/Chisinau" }],
    politicalRegime: "República parlamentar",
    population: 2512758,
    languages: ["Romeno"],
  },
  {
    id: "mc",
    continent: "europe",
    name: "Mônaco",
    capital: "Mônaco",
    capitalLatitude: 43.7384,
    capitalLongitude: 7.4246,
    capitalTimezone: "Europe/Monaco",
    timezones: [{ id: "capital", label: "Mônaco (CET/CEST)", timezone: "Europe/Monaco" }],
    politicalRegime: "Monarquia constitucional",
    population: 36297,
    languages: ["Francês"],
  },
  {
    id: "me",
    continent: "europe",
    name: "Montenegro",
    capital: "Podgorica",
    capitalLatitude: 42.4304,
    capitalLongitude: 19.2594,
    capitalTimezone: "Europe/Podgorica",
    timezones: [{ id: "capital", label: "Podgorica (CET/CEST)", timezone: "Europe/Podgorica" }],
    politicalRegime: "República parlamentar",
    population: 616177,
    languages: ["Montenegrino"],
  },
  {
    id: "no",
    continent: "europe",
    name: "Noruega",
    capital: "Oslo",
    capitalLatitude: 59.9139,
    capitalLongitude: 10.7522,
    capitalTimezone: "Europe/Oslo",
    timezones: [{ id: "capital", label: "Oslo (CET/CEST)", timezone: "Europe/Oslo" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 5550203,
    languages: ["Norueguês"],
  },
  {
    id: "pl",
    continent: "europe",
    name: "Polônia",
    capital: "Varsóvia",
    capitalLatitude: 52.2297,
    capitalLongitude: 21.0122,
    capitalTimezone: "Europe/Warsaw",
    timezones: [{ id: "capital", label: "Varsóvia (CET/CEST)", timezone: "Europe/Warsaw" }],
    politicalRegime: "República parlamentar",
    population: 36753736,
    languages: ["Polonês"],
  },
  {
    id: "pt",
    continent: "europe",
    name: "Portugal",
    capital: "Lisboa",
    capitalLatitude: 38.7223,
    capitalLongitude: -9.1393,
    capitalTimezone: "Europe/Lisbon",
    timezones: [
      { id: "capital", label: "Lisboa (WET/WEST)", timezone: "Europe/Lisbon" },
      { id: "azores", label: "Açores (AZOT/AZOST)", timezone: "Atlantic/Azores" },
    ],
    politicalRegime: "República semipresidencialista",
    population: 10352042,
    languages: ["Português"],
  },
  {
    id: "gb",
    continent: "europe",
    name: "Reino Unido",
    capital: "Londres",
    capitalLatitude: 51.5072,
    capitalLongitude: -0.1276,
    capitalTimezone: "Europe/London",
    timezones: [{ id: "capital", label: "Londres (GMT/BST)", timezone: "Europe/London" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 69138192,
    languages: ["Inglês"],
  },
  {
    id: "cz",
    continent: "europe",
    name: "Tchéquia",
    capital: "Praga",
    capitalLatitude: 50.0755,
    capitalLongitude: 14.4378,
    capitalTimezone: "Europe/Prague",
    timezones: [{ id: "capital", label: "Praga (CET/CEST)", timezone: "Europe/Prague" }],
    politicalRegime: "República parlamentar",
    population: 10827529,
    languages: ["Tcheco"],
    aliases: ["República Tcheca"],
  },
  {
    id: "ro",
    continent: "europe",
    name: "Romênia",
    capital: "Bucareste",
    capitalLatitude: 44.4268,
    capitalLongitude: 26.1025,
    capitalTimezone: "Europe/Bucharest",
    timezones: [{ id: "capital", label: "Bucareste (EET/EEST)", timezone: "Europe/Bucharest" }],
    politicalRegime: "República semipresidencialista",
    population: 19051562,
    languages: ["Romeno"],
  },
  {
    id: "sm",
    continent: "europe",
    name: "San Marino",
    capital: "San Marino",
    capitalLatitude: 43.9424,
    capitalLongitude: 12.4578,
    capitalTimezone: "Europe/San_Marino",
    timezones: [{ id: "capital", label: "San Marino (CET/CEST)", timezone: "Europe/San_Marino" }],
    politicalRegime: "República parlamentar",
    population: 33642,
    languages: ["Italiano"],
  },
  {
    id: "rs",
    continent: "europe",
    name: "Sérvia",
    capital: "Belgrado",
    capitalLatitude: 44.7866,
    capitalLongitude: 20.4489,
    capitalTimezone: "Europe/Belgrade",
    timezones: [{ id: "capital", label: "Belgrado (CET/CEST)", timezone: "Europe/Belgrade" }],
    politicalRegime: "República parlamentar",
    population: 6647003,
    languages: ["Sérvio"],
  },
  {
    id: "se",
    continent: "europe",
    name: "Suécia",
    capital: "Estocolmo",
    capitalLatitude: 59.3293,
    capitalLongitude: 18.0686,
    capitalTimezone: "Europe/Stockholm",
    timezones: [{ id: "capital", label: "Estocolmo (CET/CEST)", timezone: "Europe/Stockholm" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 10551707,
    languages: ["Sueco"],
  },
  {
    id: "ch",
    continent: "europe",
    name: "Suíça",
    capital: "Berna",
    capitalLatitude: 46.9480,
    capitalLongitude: 7.4474,
    capitalTimezone: "Europe/Zurich",
    timezones: [{ id: "capital", label: "Berna (CET/CEST)", timezone: "Europe/Zurich" }],
    politicalRegime: "República federal diretorial",
    population: 8960285,
    languages: ["Alemão", "Francês", "Italiano", "Romanche"],
  },
  {
    id: "ua",
    continent: "europe",
    name: "Ucrânia",
    capital: "Kiev",
    capitalLatitude: 50.4501,
    capitalLongitude: 30.5234,
    capitalTimezone: "Europe/Kyiv",
    timezones: [{ id: "capital", label: "Kiev (EET/EEST)", timezone: "Europe/Kyiv" }],
    politicalRegime: "República semipresidencialista",
    population: 36744636,
    languages: ["Ucraniano"],
  },
  {
    id: "va",
    continent: "europe",
    name: "Vaticano",
    capital: "Cidade do Vaticano",
    capitalLatitude: 41.9029,
    capitalLongitude: 12.4534,
    capitalTimezone: "Europe/Vatican",
    timezones: [{ id: "capital", label: "Vaticano (CET/CEST)", timezone: "Europe/Vatican" }],
    politicalRegime: "Teocracia eletiva",
    population: 825,
    languages: ["Italiano", "Latim"],
  },

  // ════════════════════════════════════════════
  // OCEANIA
  // ════════════════════════════════════════════
  {
    id: "au",
    continent: "oceania",
    name: "Austrália",
    capital: "Canberra",
    capitalLatitude: -35.2809,
    capitalLongitude: 149.1300,
    capitalTimezone: "Australia/Sydney",
    timezones: [
      { id: "capital", label: "Canberra / Sydney (AEST/AEDT)", timezone: "Australia/Sydney" },
      { id: "adelaide", label: "Adelaide (ACST/ACDT)", timezone: "Australia/Adelaide" },
      { id: "perth", label: "Perth (AWST)", timezone: "Australia/Perth" },
      { id: "darwin", label: "Darwin (ACST)", timezone: "Australia/Darwin" },
    ],
    politicalRegime: "Monarquia constitucional parlamentar federal",
    population: 26918496,
    languages: ["Inglês"],
  },
  {
    id: "fj",
    continent: "oceania",
    name: "Fiji",
    capital: "Suva",
    capitalLatitude: -18.1416,
    capitalLongitude: 178.4419,
    capitalTimezone: "Pacific/Fiji",
    timezones: [{ id: "capital", label: "Suva (FJT)", timezone: "Pacific/Fiji" }],
    politicalRegime: "República parlamentar",
    population: 936375,
    languages: ["Inglês", "Fijiano", "Hindi fijiano"],
  },
  {
    id: "ki",
    continent: "oceania",
    name: "Kiribati",
    capital: "Tarawa Sul",
    capitalLatitude: 1.4518,
    capitalLongitude: 173.0186,
    capitalTimezone: "Pacific/Tarawa",
    timezones: [{ id: "capital", label: "Tarawa (GILT)", timezone: "Pacific/Tarawa" }],
    politicalRegime: "República presidencialista",
    population: 131232,
    languages: ["Inglês", "Gilbertês"],
  },
  {
    id: "mh",
    continent: "oceania",
    name: "Ilhas Marshall",
    capital: "Majuro",
    capitalLatitude: 7.1164,
    capitalLongitude: 171.1858,
    capitalTimezone: "Pacific/Majuro",
    timezones: [{ id: "capital", label: "Majuro (MHT)", timezone: "Pacific/Majuro" }],
    politicalRegime: "República presidencialista",
    population: 42050,
    languages: ["Marshalês", "Inglês"],
  },
  {
    id: "sb",
    continent: "oceania",
    name: "Ilhas Salomão",
    capital: "Honiara",
    capitalLatitude: -9.4456,
    capitalLongitude: 159.9729,
    capitalTimezone: "Pacific/Guadalcanal",
    timezones: [{ id: "capital", label: "Honiara (SBT)", timezone: "Pacific/Guadalcanal" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 724273,
    languages: ["Inglês"],
  },
  {
    id: "fm",
    continent: "oceania",
    name: "Micronésia",
    capital: "Palikir",
    capitalLatitude: 6.9147,
    capitalLongitude: 158.1611,
    capitalTimezone: "Pacific/Pohnpei",
    timezones: [{ id: "capital", label: "Palikir (PONT)", timezone: "Pacific/Pohnpei" }],
    politicalRegime: "República federal presidencialista",
    population: 113131,
    languages: ["Inglês"],
  },
  {
    id: "nr",
    continent: "oceania",
    name: "Nauru",
    capital: "Yaren",
    capitalLatitude: -0.5477,
    capitalLongitude: 166.9209,
    capitalTimezone: "Pacific/Nauru",
    timezones: [{ id: "capital", label: "Yaren (NRT)", timezone: "Pacific/Nauru" }],
    politicalRegime: "República parlamentar",
    population: 12780,
    languages: ["Nauruano", "Inglês"],
  },
  {
    id: "nz",
    continent: "oceania",
    name: "Nova Zelândia",
    capital: "Wellington",
    capitalLatitude: -41.2866,
    capitalLongitude: 174.7756,
    capitalTimezone: "Pacific/Auckland",
    timezones: [
      { id: "capital", label: "Wellington (NZST/NZDT)", timezone: "Pacific/Auckland" },
      { id: "chatham", label: "Chatham (CHAST/CHADT)", timezone: "Pacific/Chatham" },
    ],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 5228100,
    languages: ["Inglês", "Maori"],
  },
  {
    id: "pg",
    continent: "oceania",
    name: "Papua Nova Guiné",
    capital: "Port Moresby",
    capitalLatitude: -6.3149,
    capitalLongitude: 143.9556,
    capitalTimezone: "Pacific/Port_Moresby",
    timezones: [{ id: "capital", label: "Port Moresby (PGT)", timezone: "Pacific/Port_Moresby" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 10329931,
    languages: ["Inglês", "Tok Pisin", "Hiri Motu"],
  },
  {
    id: "ws",
    continent: "oceania",
    name: "Samoa",
    capital: "Apia",
    capitalLatitude: -13.8333,
    capitalLongitude: -171.7500,
    capitalTimezone: "Pacific/Apia",
    timezones: [{ id: "capital", label: "Apia (WST)", timezone: "Pacific/Apia" }],
    politicalRegime: "República parlamentar",
    population: 222382,
    languages: ["Samoano", "Inglês"],
  },
  {
    id: "to",
    continent: "oceania",
    name: "Tonga",
    capital: "Nukualofa",
    capitalLatitude: -21.2087,
    capitalLongitude: -175.1982,
    capitalTimezone: "Pacific/Tongatapu",
    timezones: [{ id: "capital", label: "Nukualofa (TOT)", timezone: "Pacific/Tongatapu" }],
    politicalRegime: "Monarquia constitucional",
    population: 106858,
    languages: ["Tonganês", "Inglês"],
  },
  {
    id: "tv",
    continent: "oceania",
    name: "Tuvalu",
    capital: "Funafuti",
    capitalLatitude: -8.5211,
    capitalLongitude: 179.1962,
    capitalTimezone: "Pacific/Funafuti",
    timezones: [{ id: "capital", label: "Funafuti (TVT)", timezone: "Pacific/Funafuti" }],
    politicalRegime: "Monarquia constitucional parlamentar",
    population: 11312,
    languages: ["Tuvaluano", "Inglês"],
  },
  {
    id: "vu",
    continent: "oceania",
    name: "Vanuatu",
    capital: "Port Vila",
    capitalLatitude: -17.7333,
    capitalLongitude: 168.3167,
    capitalTimezone: "Pacific/Efate",
    timezones: [{ id: "capital", label: "Port Vila (VUT)", timezone: "Pacific/Efate" }],
    politicalRegime: "República parlamentar",
    population: 326740,
    languages: ["Bislama", "Inglês", "Francês"],
  },
];

// ── Derived lookups ──

export const WORLD_CLOCK_COUNTRY_BY_ID = Object.fromEntries(
  WORLD_CLOCK_COUNTRIES.map(country => [country.id, country])
) as Record<string, WorldCountryDefinition>;

export const COUNTRIES_BY_CONTINENT: Record<Continent, WorldCountryDefinition[]> =
  CONTINENT_ORDER.reduce(
    (acc, continent) => {
      acc[continent] = WORLD_CLOCK_COUNTRIES.filter(c => c.continent === continent).sort(
        (a, b) => a.name.localeCompare(b.name, "pt-BR")
      );
      return acc;
    },
    {} as Record<Continent, WorldCountryDefinition[]>
  );

export function getCountryById(countryId: string): WorldCountryDefinition {
  return WORLD_CLOCK_COUNTRY_BY_ID[countryId] ?? WORLD_CLOCK_COUNTRY_BY_ID["br"];
}

export function getCountryTimezoneOption(
  country: WorldCountryDefinition,
  timezoneId: string | null | undefined
): CountryTimezoneOption {
  return (
    country.timezones.find(option => option.id === timezoneId) ??
    country.timezones[0]
  );
}
